# Optuna — Automated Hyperparameter Optimization

## What is Optuna?
**Optuna** is an automatic hyperparameter optimization framework — it finds the best hyperparameters for your ML model by running many trials intelligently.

### The Problem It Solves
Manual tuning or Grid Search wastes time:
- **Grid Search**: tries every combination → O(n^k) trials, most wasted
- **Random Search**: random combinations → better, but still blind
- **Optuna (Bayesian)**: learns from previous trials → focuses on promising regions

### Core Concepts
| Concept | Meaning |
|---------|---------|
| **Trial** | One run of the objective function with one set of hyperparameters |
| **Study** | A collection of trials — the full optimization run |
| **Objective function** | The function Optuna calls each trial; returns a score to minimize/maximize |
| **Sampler** | The strategy for choosing the next hyperparameter values |
| **Pruner** | Stops unpromising trials early to save time |

### What This Notebook Covers
1. Basic Optuna setup — TPE sampler on Random Forest
2. Samplers: TPE vs Random vs Grid
3. Visualizations — optimization history, parallel coordinates, importance
4. Multi-model search — SVM / RF / Gradient Boosting in one study
5. XGBoost with pruning — stop bad trials early

## Step 1: Install Optuna

In [38]:
!pip install optuna

Requirement already satisfied: optuna in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna) (1.18.5)
Requirement already satisfied: colorlog in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna) (6.11.0)
Requirement already satisfied: numpy in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna) (2.4.5)
Requirement already satisfied: packaging>=20.0 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)
Requirement already satisfied: colorama in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.5)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## Step 2: Load the Pima Indians Diabetes Dataset

**Dataset:** Pima Indians Diabetes (UCI Repository)
- 768 patients, 8 features, binary outcome (diabetic or not)

| Feature | Description |
|---------|-------------|
| Pregnancies | Number of pregnancies |
| Glucose | Plasma glucose concentration |
| BloodPressure | Diastolic blood pressure (mmHg) |
| SkinThickness | Triceps skinfold thickness (mm) |
| Insulin | 2-hour serum insulin |
| BMI | Body mass index |
| DiabetesPedigreeFunction | Genetic diabetes risk score |
| Age | Age in years |
| **Outcome** | **1 = diabetic, 0 = not diabetic** |

In [39]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

## Step 3: Clean Missing Values
Several columns use **0 as a placeholder for missing data** (e.g. Glucose=0 is medically impossible).

Fix: replace 0 → NaN → impute with column mean.

In [40]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

## Step 4: Train/Test Split + Feature Scaling
- 70% train, 30% test
- `StandardScaler` normalises features to mean=0, std=1 → helps most models converge faster

In [41]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

---
## Part 1: Basic Optuna — TPE Sampler

### What is TPE (Tree-structured Parzen Estimator)?
TPE is Optuna's **default and most powerful sampler**.

**How it works:**
1. First few trials → random exploration (like Random Search)
2. After gathering data → splits trials into "good" (top 25%) and "bad" (bottom 75%)
3. Fits two distributions: one over good hyperparameters, one over bad
4. Next trial = maximize `P(good) / P(bad)` → focuses on promising regions

**Result:** Far fewer trials needed compared to Grid or Random Search.

### The Objective Function
The objective function is called once per trial. It:
1. Receives a `trial` object
2. Uses `trial.suggest_*()` to pick hyperparameter values
3. Trains and evaluates a model
4. Returns the score (Optuna tries to maximize or minimize this)

```python
trial.suggest_int('n_estimators', 50, 200)   # integer in [50, 200]
trial.suggest_float('C', 0.01, 100, log=True) # float, log scale
trial.suggest_categorical('kernel', ['rbf', 'linear'])
```

In [42]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

### Create Study & Run 50 Trials
- `direction='maximize'` — we want to maximize accuracy
- `TPESampler` — Bayesian optimization strategy
- `n_trials=50` — run 50 evaluations

Each trial prints its result. Watch the best value climb as Optuna learns.

In [43]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-07-19 09:02:17,716] A new study created in memory with name: no-name-0f9184fd-e340-479e-a6c6-22e154948af1
[I 2026-07-19 09:02:18,428] Trial 0 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 130, 'max_depth': 11}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-07-19 09:02:19,187] Trial 1 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 136, 'max_depth': 10}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-07-19 09:02:19,570] Trial 2 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 71, 'max_depth': 14}. Best is trial 2 with value: 0.7690875232774674.
[I 2026-07-19 09:02:20,392] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 149, 'max_depth': 10}. Best is trial 2 with value: 0.7690875232774674.
[I 2026-07-19 09:02:21,112] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 160, 'max_depth': 12}. Best is trial 4 with value: 0.7709497206703911.
[I 2026-07-19 09:02:21,966] Trial 5 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 149, 'max_depth': 10}. Best is trial 4 with value: 0.7709497206703911.
[I 2026-07-19 09:02:22,631] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 121, 'max_depth': 6}. Best is trial 4 with value: 0.7709497206703911.
[I 2026-07-19 09:02:23,180] Trial 7 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 109, 'max_depth': 17}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-07-19 09:02:23,933] Trial 8 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 119, 'max_depth': 17}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:24,530] Trial 9 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 138, 'max_depth': 7}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:25,367] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:25,776] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 88, 'max_depth': 18}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:26,257] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 103, 'max_depth': 16}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:26,903] Trial 13 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 95, 'max_depth': 16}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:27,469] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 57, 'max_depth': 20}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:27,967] Trial 15 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 110, 'max_depth': 16}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:28,699] Trial 16 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 173, 'max_depth': 3}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:29,082] Trial 17 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 84, 'max_depth': 14}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:29,686] Trial 18 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 115, 'max_depth': 14}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:30,017] Trial 19 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 52, 'max_depth': 18}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:30,506] Trial 20 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 79, 'max_depth': 13}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:31,384] Trial 21 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 115, 'max_depth': 17}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:32,390] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 101, 'max_depth': 16}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:33,091] Trial 23 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 122, 'max_depth': 18}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:33,663] Trial 24 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 109, 'max_depth': 15}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:34,256] Trial 25 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 124, 'max_depth': 19}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:34,626] Trial 26 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 73, 'max_depth': 16}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:35,427] Trial 27 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 145, 'max_depth': 17}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:35,839] Trial 28 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 91, 'max_depth': 19}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:36,606] Trial 29 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 163, 'max_depth': 12}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:37,261] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 130, 'max_depth': 15}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:37,916] Trial 31 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 117, 'max_depth': 18}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:39,049] Trial 32 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 126, 'max_depth': 17}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:39,906] Trial 33 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 19}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:40,476] Trial 34 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 112, 'max_depth': 15}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:40,982] Trial 35 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 18}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:41,700] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 20}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:42,406] Trial 37 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 120, 'max_depth': 13}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:43,206] Trial 38 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 130, 'max_depth': 17}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:44,027] Trial 39 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 157, 'max_depth': 15}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:44,555] Trial 40 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 106, 'max_depth': 9}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:45,209] Trial 41 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 110, 'max_depth': 14}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:45,677] Trial 42 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 99, 'max_depth': 15}. Best is trial 8 with value: 0.7783985102420856.
[I 2026-07-19 09:02:46,285] Trial 43 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 128, 'max_depth': 17}. Best is trial 43 with value: 0.7783985102420857.
[I 2026-07-19 09:02:47,206] Trial 44 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 131, 'max_depth': 17}. Best is trial 44 with value: 0.7802607076350093.
[I 2026-07-19 09:02:48,698] Trial 45 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 153, 'max_depth': 17}. Best is trial 44 with value: 0.7802607076350093.
[I 2026-07-19 09:02:49,378] Trial 46 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 140, 'max_depth': 16}. Best is trial 44 with value: 0.7802607076350093.
[I 2026-07-19 09:02:50,002] Trial 47 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 132, 'max_depth': 19}. Best is trial 44 with value: 0.7802607076350093.
[I 2026-07-19 09:02:50,944] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 185, 'max_depth': 13}. Best is trial 44 with value: 0.7802607076350093.
[I 2026-07-19 09:02:51,636] Trial 49 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 17}. Best is trial 44 with value: 0.7802607076350093.

### Best Trial Result

In [44]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 131, 'max_depth': 17}

### Train Final Model with Best Hyperparameters
Use the best hyperparameters found by Optuna to train on the full training set and evaluate on held-out test data.

In [45]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

---
## Part 2: Samplers in Optuna

A **sampler** controls how Optuna picks the next set of hyperparameters to try.

| Sampler | Strategy | Best for |
|---------|----------|---------|
| **TPESampler** (default) | Bayesian — learns from past trials | Most cases — efficient |
| **RandomSampler** | Pure random | Baseline comparison, parallel search |
| **GridSampler** | Exhaustive grid | Small, well-defined search spaces |
| **CmaEsSampler** | Evolution strategy | Continuous parameters, large spaces |

### 2a: Random Sampler
Picks hyperparameters uniformly at random — no learning between trials. Useful as a baseline.

In [46]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [47]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-07-19 09:02:52,044] A new study created in memory with name: no-name-45766cc4-3956-4fb6-bf5b-a3d9338045dd
[I 2026-07-19 09:02:52,401] Trial 0 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 60, 'max_depth': 9}. Best is trial 0 with value: 0.7672253258845437.
[I 2026-07-19 09:02:52,802] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 86, 'max_depth': 5}. Best is trial 0 with value: 0.7672253258845437.
[I 2026-07-19 09:02:53,344] Trial 2 finished with value: 0.7821229050279331 and parameters: {'n_estimators': 73, 'max_depth': 20}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:02:54,828] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 20}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:02:55,172] Trial 4 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 61, 'max_depth': 5}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:02:55,632] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 93, 'max_depth': 18}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:02:55,894] Trial 6 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 58, 'max_depth': 4}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:02:56,662] Trial 7 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 152, 'max_depth': 18}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:02:57,402] Trial 8 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 142, 'max_depth': 9}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:02:58,062] Trial 9 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 146, 'max_depth': 9}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:02:59,237] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 190, 'max_depth': 7}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:00,172] Trial 11 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 190, 'max_depth': 16}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:00,818] Trial 12 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 108, 'max_depth': 14}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:01,352] Trial 13 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 115, 'max_depth': 19}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:01,808] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 109, 'max_depth': 4}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:02,252] Trial 15 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 98, 'max_depth': 4}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:03,162] Trial 16 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 182, 'max_depth': 18}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:03,635] Trial 17 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 94, 'max_depth': 11}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:04,622] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 180, 'max_depth': 18}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:05,281] Trial 19 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 133, 'max_depth': 5}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:05,792] Trial 20 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 118, 'max_depth': 3}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:06,652] Trial 21 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 187, 'max_depth': 6}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:07,072] Trial 22 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 101, 'max_depth': 7}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:07,765] Trial 23 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 136, 'max_depth': 12}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:08,122] Trial 24 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 66, 'max_depth': 5}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:09,507] Trial 25 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 195, 'max_depth': 8}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:09,924] Trial 26 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 89, 'max_depth': 11}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:10,472] Trial 27 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 110, 'max_depth': 8}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:10,964] Trial 28 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 108, 'max_depth': 9}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:11,674] Trial 29 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 163, 'max_depth': 7}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:12,604] Trial 30 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 194, 'max_depth': 6}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:13,472] Trial 31 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 175, 'max_depth': 13}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:14,088] Trial 32 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 144, 'max_depth': 12}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:14,412] Trial 33 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 59, 'max_depth': 18}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:14,802] Trial 34 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 65, 'max_depth': 16}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:15,531] Trial 35 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 125, 'max_depth': 10}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:16,571] Trial 36 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 186, 'max_depth': 16}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:17,469] Trial 37 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 178, 'max_depth': 14}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:17,746] Trial 38 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 55, 'max_depth': 16}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:18,021] Trial 39 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 57, 'max_depth': 11}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:19,117] Trial 40 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 162, 'max_depth': 8}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:19,654] Trial 41 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 72, 'max_depth': 5}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:20,169] Trial 42 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 93, 'max_depth': 14}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:20,941] Trial 43 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 192, 'max_depth': 3}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:21,849] Trial 44 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 187, 'max_depth': 19}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:22,482] Trial 45 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 154, 'max_depth': 5}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:23,153] Trial 46 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 156, 'max_depth': 8}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:23,992] Trial 47 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 185, 'max_depth': 11}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:24,553] Trial 48 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 122, 'max_depth': 5}. Best is trial 2 with value: 0.7821229050279331.
[I 2026-07-19 09:03:24,882] Trial 49 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 69, 'max_depth': 10}. Best is trial 2 with value: 0.7821229050279331.

In [48]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279331
Best hyperparameters: {'n_estimators': 73, 'max_depth': 20}

In [49]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

### 2b: Grid Sampler
Exhaustively tries every combination in a predefined search space.

```
search_space = {n_estimators: [50,100,150,200], max_depth: [5,10,15,20]}
→ 4 × 4 = 16 total combinations — all will be tried
```

**When to use:** Small search space where you want guaranteed coverage.
**Avoid when:** Space is large — becomes exponentially expensive.

In [50]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [51]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-07-19 09:03:25,155] A new study created in memory with name: no-name-ddd8b544-c821-4c8a-abaf-5fca68c70fae
[I 2026-07-19 09:03:25,617] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-07-19 09:03:26,287] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-07-19 09:03:26,532] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-19 09:03:26,982] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-19 09:03:27,532] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-19 09:03:27,762] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-19 09:03:28,427] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-19 09:03:29,354] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-19 09:03:30,332] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-19 09:03:31,496] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-19 09:03:32,817] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-19 09:03:33,744] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-19 09:03:34,782] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-19 09:03:35,052] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-07-19 09:03:35,592] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-07-19 09:03:35,881] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [52]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [53]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

---
## Part 3: Optuna Visualizations

Optuna provides interactive Plotly charts to understand the optimization process.

## Optuna Visualizations

### Import Visualization Tools

In [54]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

### 1. Optimization History
Shows the **objective value** (accuracy) over each trial.
- Dots = individual trial scores
- Line = best score seen so far
- Look for: rapid improvement early → plateauing → good convergence

In [55]:
# 1. Optimization History
plot_optimization_history(study).show()

### 2. Parallel Coordinates Plot
Shows all trials as lines crossing vertical axes (one axis per hyperparameter).
- Lines that end at high accuracy = good hyperparameter combinations
- Cluster of good lines → stable region of the search space
- Useful for spotting which parameter ranges consistently perform well

In [56]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

### 3. Slice Plot
Shows how accuracy changes as **one hyperparameter varies** (others held constant).
- Each subplot = one hyperparameter
- Look for: clear peaks → optimal value range visible

In [57]:
# 3. Slice Plot
plot_slice(study).show()

### 4. Contour Plot
Shows the **interaction between two hyperparameters** as a heatmap.
- Bright regions = high accuracy combinations
- Useful for understanding parameter interactions (e.g. high n_estimators + low max_depth)

In [58]:
# 4. Contour Plot
plot_contour(study).show()

### 5. Hyperparameter Importance
Ranks which hyperparameters had the most impact on the objective score.
- Computed using **fANOVA** (functional ANOVA) over all trials
- High importance → tuning that parameter matters a lot
- Low importance → that parameter is not critical for this dataset/model

In [59]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

---
## Part 4: Optimizing Multiple ML Models in One Study

Instead of running separate studies for each model, put **all models in one objective function**.
Optuna simultaneously searches across:
- Which model to use (SVM, Random Forest, Gradient Boosting)
- The best hyperparameters for each model

### Key Trick: `suggest_categorical` for Model Selection
```python
classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])
```
Optuna treats model choice as just another hyperparameter — it learns which model tends to perform better.

### Hyperparameters per Model
| Model | Hyperparameters Tuned |
|-------|----------------------|
| SVM | C, kernel, gamma |
| Random Forest | n_estimators, max_depth, min_samples_split, min_samples_leaf, bootstrap |
| Gradient Boosting | n_estimators, learning_rate, max_depth, min_samples_split, min_samples_leaf |

## Optimizing Multiple ML Models

### Imports

In [60]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

### Multi-Model Objective Function

In [61]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

### Run 100 Trials Across All Models

In [62]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-07-19 09:03:36,586] A new study created in memory with name: no-name-216ab559-2dd1-4d62-8f67-1d9c0d8fafb0
[I 2026-07-19 09:03:36,624] Trial 0 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.22210522924704215, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-07-19 09:03:38,155] Trial 1 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 246, 'learning_rate': 0.2364019270414651, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-07-19 09:03:38,456] Trial 2 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 2 with value: 0.7672253258845437.
[I 2026-07-19 09:03:38,485] Trial 3 finished with value: 0.7579143389199254 and parameters: {'classifier': 'SVM', 'C': 4.488367493156473, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 2 with value: 0.7672253258845437.
[I 2026-07-19 09:03:38,569] Trial 4 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 20.057992814606724, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:39,522] Trial 5 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 213, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:40,182] Trial 6 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 188, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:40,690] Trial 7 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 111, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:42,401] Trial 8 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 276, 'learning_rate': 0.25809218174272897, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:43,412] Trial 9 finished with value: 0.7523277467411544 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 164, 'learning_rate': 0.07370274521191464, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:43,615] Trial 10 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 60.28870443530676, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:43,901] Trial 11 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 97.80270463601215, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:44,103] Trial 12 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 50.756150333260116, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:44,164] Trial 13 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.89409627332589, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:44,202] Trial 14 finished with value: 0.7132216014897579 and parameters: {'classifier': 'SVM', 'C': 12.92079664552714, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:44,272] Trial 15 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 18.177018581464022, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:44,301] Trial 16 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.8307038749799653, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:44,352] Trial 17 finished with value: 0.7039106145251397 and parameters: {'classifier': 'SVM', 'C': 25.934773754853488, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:44,391] Trial 18 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 3.456503878207226, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:46,795] Trial 19 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 297, 'learning_rate': 0.010223019846518033, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:46,812] Trial 20 finished with value: 0.6834264432029795 and parameters: {'classifier': 'SVM', 'C': 97.11437772570865, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:47,112] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 89.4313883393747, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:47,249] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 37.08202865223165, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:47,390] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 42.6430560643717, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:47,437] Trial 24 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.941775765048095, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:47,695] Trial 25 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 81.76054621300051, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:47,812] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 36.969725482766606, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:47,853] Trial 27 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.41445894967341207, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:48,347] Trial 28 finished with value: 0.7672253258845437 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 131, 'learning_rate': 0.010555645790970423, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 8}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:48,632] Trial 29 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 55, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:48,682] Trial 30 finished with value: 0.7057728119180634 and parameters: {'classifier': 'SVM', 'C': 21.25023859313588, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:48,859] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 44.81771730432334, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:49,062] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 55.71452287792304, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:49,291] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 67.59979272684933, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:49,417] Trial 34 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 25.726022805431896, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:49,437] Trial 35 finished with value: 0.696461824953445 and parameters: {'classifier': 'SVM', 'C': 8.566835572278032, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:49,837] Trial 36 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 108, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:52,829] Trial 37 finished with value: 0.6945996275605214 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 227, 'learning_rate': 0.03917575847563875, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:53,541] Trial 38 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 160, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:53,707] Trial 39 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 50.121976602940855, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:53,981] Trial 40 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 94.50934088776367, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:54,071] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 15.07550422856573, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:54,122] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.945374087079761, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:54,214] Trial 43 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 28.92209880441286, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:54,237] Trial 44 finished with value: 0.6778398510242085 and parameters: {'classifier': 'SVM', 'C': 13.001978398611422, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:54,414] Trial 45 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 53.14616585600607, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:56,878] Trial 46 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 262, 'learning_rate': 0.04167779176872601, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:57,178] Trial 47 finished with value: 0.7486033519553074 and parameters: {'classifier': 'RandomForest', 'n_estimators': 86, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:57,264] Trial 48 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 4.03518229209627, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:57,382] Trial 49 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 29.413498658168095, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:57,415] Trial 50 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 14.854284110616376, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:57,525] Trial 51 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 21.14993162008948, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-07-19 09:03:57,549] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13103309847801292, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:03:57,570] Trial 53 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.31751954965534596, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:03:57,582] Trial 54 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1348951082500075, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:03:57,602] Trial 55 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11684939658985873, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:03:57,632] Trial 56 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13627013055411588, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:03:57,649] Trial 57 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1150135035733665, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:03:57,671] Trial 58 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11372760427692583, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:03:57,682] Trial 59 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10002368430303833, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:00,662] Trial 60 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 192, 'learning_rate': 0.10062154151561693, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:00,683] Trial 61 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10043325827340562, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:00,711] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11441773808552401, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:00,733] Trial 63 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16445596804712506, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:00,757] Trial 64 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17907092580313316, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:00,788] Trial 65 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.14083999411345727, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:00,812] Trial 66 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.27969271378999216, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:00,857] Trial 67 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.4749841403915402, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:01,472] Trial 68 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 150, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:01,501] Trial 69 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13329848181861023, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:01,541] Trial 70 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 0.23172897581446877, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:01,584] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13104015986881304, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:01,629] Trial 72 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.20423641511321206, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:01,661] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1324264663618708, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:01,684] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1184414994452275, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:01,717] Trial 75 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24014403441561166, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:01,746] Trial 76 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16871188175101365, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:02,561] Trial 77 finished with value: 0.7597765363128492 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 91, 'learning_rate': 0.025559080462458774, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:02,581] Trial 78 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.311347694181973, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:02,601] Trial 79 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.45876401843479353, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:02,650] Trial 80 finished with value: 0.7486033519553073 and parameters: {'classifier': 'SVM', 'C': 0.1476051306146913, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.
[I 2026-07-19 09:04:02,701] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11977946837220237, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 52 with value: 0.7895716945996275.

### Best Trial — Winner Model & Parameters

In [63]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.13103309847801292, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

### All Trials as a DataFrame
Each row = one trial. Columns show hyperparameter values and the accuracy score.

In [64]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.763501,2026-07-19 09:03:36.588979,2026-07-19 09:03:36.624443,0 days 00:00:00.035464,0.222105,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.737430,2026-07-19 09:03:36.624443,2026-07-19 09:03:38.155879,0 days 00:00:01.531436,NaN,NaN,GradientBoosting,NaN,NaN,0.236402,5.0,7.0,9.0,246.0,COMPLETE
2,2,0.767225,2026-07-19 09:03:38.155879,2026-07-19 09:03:38.456124,0 days 00:00:00.300245,NaN,False,RandomForest,NaN,NaN,NaN,12.0,6.0,8.0,64.0,COMPLETE
3,3,0.757914,2026-07-19 09:03:38.456124,2026-07-19 09:03:38.485650,0 days 00:00:00.029526,4.488367,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,0.785847,2026-07-19 09:03:38.485650,2026-07-19 09:03:38.569252,0 days 00:00:00.083602,20.057993,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.789572,2026-07-19 09:04:06.885628,2026-07-19 09:04:06.911729,0 days 00:00:00.026101,0.120200,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.789572,2026-07-19 09:04:06.911729,2026-07-19 09:04:06.940191,0 days 00:00:00.028462,0.140759,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.785847,2026-07-19 09:04:06.941698,2026-07-19 09:04:06.961661,0 days 00:00:00.019963,0.272780,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.787709,2026-07-19 09:04:06.969013,2026-07-19 09:04:07.003114,0 days 00:00:00.034101,0.103268,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.787709,2026-07-19 09:04:07.003114,2026-07-19 09:04:07.031655,0 days 00:00:00.028541,0.172154,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

### How Many Trials Did Each Model Get?
Optuna allocates more trials to models that seem promising.

In [65]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 80
GradientBoosting    10
RandomForest        10
Name: count, dtype: int64

### Average Accuracy by Model
Compare which model generally performed best across its trials.

In [66]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.744879
RandomForest        0.763315
SVM                 0.775256
Name: value, dtype: float64

### Optimization History — Multi-Model

In [67]:
# 1. Optimization History
plot_optimization_history(study).show()

### Slice Plot — Multi-Model
See how each hyperparameter affects accuracy within its model.

In [68]:
# 3. Slice Plot
plot_slice(study).show()

### Hyperparameter Importance — Multi-Model
Which hyperparameter (across all models) had the biggest impact?

In [69]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

---
## Part 5: XGBoost with Pruning (SuccessiveHalvingPruner)

### What is Pruning?
**Pruning** stops unpromising trials **early** — before they finish all boosting rounds.

```
Without pruning: every trial trains for 300 rounds
With pruning:    bad trials stopped at round 30, 60, etc. → 10× faster
```

### SuccessiveHalvingPruner
At each checkpoint:
- Keep only the top 50% of trials (by current performance)
- Discard the rest
- Allocate remaining budget to survivors

### XGBoost Hyperparameters Being Tuned
| Parameter | Role |
|-----------|------|
| `lambda` | L2 regularisation — prevents overfitting |
| `alpha` | L1 regularisation — sparsity |
| `eta` | Learning rate — step size per tree |
| `gamma` | Min loss reduction to split a node |
| `max_depth` | Tree depth — complexity |
| `min_child_weight` | Min samples in a leaf |
| `subsample` | Row sampling per tree |
| `colsample_bytree` | Feature sampling per tree |

### Dataset: Iris (3-class classification)
Uses `multi:softprob` objective — outputs probability for each of 3 classes.
`eval-mlogloss` = multi-class log loss used for pruning decisions.

In [70]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    from optuna_integration.xgboost import XGBoostPruningCallback
    pruning_callback = XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2026-07-19 09:04:07,659] A new study created in memory with name: no-name-51d35b29-6f15-4952-8dca-3c9cd3e6cf4f

[0]	train-mlogloss:1.06933	eval-mlogloss:1.06977
[1]	train-mlogloss:1.05370	eval-mlogloss:1.05279
[2]	train-mlogloss:1.03500	eval-mlogloss:1.03596
[3]	train-mlogloss:1.00336	eval-mlogloss:1.00203
[4]	train-mlogloss:0.98982	eval-mlogloss:0.98729
[5]	train-mlogloss:0.96853	eval-mlogloss:0.96462
[6]	train-mlogloss:0.93881	eval-mlogloss:0.93190
[7]	train-mlogloss:0.90858	eval-mlogloss:0.89902
[8]	train-mlogloss:0.89451	eval-mlogloss:0.88624
[9]	train-mlogloss:0.86499	eval-mlogloss:0.85537
[10]	train-mlogloss:0.84403	eval-mlogloss:0.83289
[11]	train-mlogloss:0.83331	eval-mlogloss:0.82360
[12]	train-mlogloss:0.81104	eval-mlogloss:0.79840
[13]	train-mlogloss:0.79287	eval-mlogloss:0.77965
[14]	train-mlogloss:0.76828	eval-mlogloss:0.75286
[15]	train-mlogloss:0.75487	eval-mlogloss:0.73919
[16]	train-mlogloss:0.74345	eval-mlogloss:0.72502
[17]	train-mlogloss:0.72531	eval-mlogloss:0.70670
[18]	train-mlogloss:0.70787	eval-mlogloss:0.68763
[19]	train-mlogloss:0.70332	eval-mlogloss:0.68373
[20]	train-mlogloss:0.69823	eval-mlogloss:0.67862
[21]	train-mlogloss:0.68362	eval-mlogloss:0.66406
[22]	train-mlogloss:0.66313	eval-mlogloss:0.64158
[23]	train-mlogloss:0.64396	eval-mlogloss:0.62111
[24]	train-mlogloss:0.62833	eval-mlogloss:0.60373
[25]	train-mlogloss:0.61014	eval-mlogloss:0.58362
[26]	train-mlogloss:0.60666	eval-mlogloss:0.58024
[27]	train-mlogloss:0.59166	eval-mlogloss:0.56409
[28]	train-mlogloss:0.58309	eval-mlogloss:0.55574
[29]	train-mlogloss:0.57367	eval-mlogloss:0.54623
[30]	train-mlogloss:0.56681	eval-mlogloss:0.54031
[31]	train-mlogloss:0.55505	eval-mlogloss:0.52789
[32]	train-mlogloss:0.54075	eval-mlogloss:0.51366
[33]	train-mlogloss:0.53593	eval-mlogloss:0.50734
[34]	train-mlogloss:0.52792	eval-mlogloss:0.49824
[35]	train-mlogloss:0.51992	eval-mlogloss:0.48941
[36]	train-mlogloss:0.51243	eval-mlogloss:0.48149
[37]	train-mlogloss:0.49883	eval-mlogloss:0.46674
[38]	train-mlogloss:0.49213	eval-mlogloss:0.45967
[39]	train-mlogloss:0.48275	eval-mlogloss:0.44905
[40]	train-mlogloss:0.47576	eval-mlogloss:0.44215
[41]	train-mlogloss:0.46718	eval-mlogloss:0.43251
[42]	train-mlogloss:0.45967	eval-mlogloss:0.42364
[43]	train-mlogloss:0.45098	eval-mlogloss:0.41427
[44]	train-mlogloss:0.44293	eval-mlogloss:0.40518
[45]	train-mlogloss:0.43206	eval-mlogloss:0.39402
[46]	train-mlogloss:0.42969	eval-mlogloss:0.39108
[47]	train-mlogloss:0.42368	eval-mlogloss:0.38357
[48]	train-mlogloss:0.41771	eval-mlogloss:0.37790
[49]	train-mlogloss:0.41154	eval-mlogloss:0.37097
[50]	train-mlogloss:0.40438	eval-mlogloss:0.36257
[51]	train-mlogloss:0.39751	eval-mlogloss:0.35528
[52]	train-mlogloss:0.39336	eval-mlogloss:0.35043
[53]	train-mlogloss:0.38486	eval-mlogloss:0.34103
[54]	train-mlogloss:0.38086	eval-mlogloss:0.33649
[55]	train-mlogloss:0.37952	eval-mlogloss:0.33581
[56]	train-mlogloss:0.37577	eval-mlogloss:0.33164
[57]	train-mlogloss:0.37102	eval-mlogloss:0.32709
[58]	train-mlogloss:0.36529	eval-mlogloss:0.32070
[59]	train-mlogloss:0.35742	eval-mlogloss:0.31134
[60]	train-mlogloss:0.35353	eval-mlogloss:0.30675
[61]	train-mlogloss:0.35067	eval-mlogloss:0.30373
[62]	train-mlogloss:0.34527	eval-mlogloss:0.29768
[63]	train-mlogloss:0.34249	eval-mlogloss:0.29439
[64]	train-mlogloss:0.33903	eval-mlogloss:0.29062
[65]	train-mlogloss:0.33576	eval-mlogloss:0.28666
[66]	train-mlogloss:0.32980	eval-mlogloss:0.28004
[67]	train-mlogloss:0.32662	eval-mlogloss:0.27681
[68]	train-mlogloss:0.32222	eval-mlogloss:0.27168
[69]	train-mlogloss:0.32092	eval-mlogloss:0.27039
[70]	train-mlogloss:0.31995	eval-mlogloss:0.26912
[71]	train-mlogloss:0.31492	eval-mlogloss:0.26387
[72]	train-mlogloss:0.31424	eval-mlogloss:0.26356
[73]	train-mlogloss:0.31165	eval-mlogloss:0.26067
[74]	train-mlogloss:0.30711	eval-mlogloss:0.25566
[75]	train-mlogloss:0.30532	eval-mlogloss:0.25378
[76]	train-mlogloss:0.30430	eval-mlogloss:0.25250
[77]	train-mlogloss:0.30065	eval-mlogloss:0.24841
[78]	train-mlogloss:0.29834	eval-mlogloss:0.24616
[79]	train-mlogloss:0.29645	eval-mlogloss:0.24383
[80]	train-mlogloss:0.29516	eval-mlogloss:0.24274
[81]	train-mlogloss:0.29346	eval-mlogloss:0.24093
[82]	train-mlogloss:0.29284	eval-mlogloss:0.24054
[83]	train-mlogloss:0.29284	eval-mlogloss:0.24054
[84]	train-mlogloss:0.28907	eval-mlogloss:0.23669
[85]	train-mlogloss:0.28872	eval-mlogloss:0.23609
[86]	train-mlogloss:0.28652	eval-mlogloss:0.23304
[87]	train-mlogloss:0.28266	eval-mlogloss:0.22872
[88]	train-mlogloss:0.28105	eval-mlogloss:0.22698
[89]	train-mlogloss:0.28050	eval-mlogloss:0.22657
[90]	train-mlogloss:0.28040	eval-mlogloss:0.22661
[91]	train-mlogloss:0.27958	eval-mlogloss:0.22603
[92]	train-mlogloss:0.27914	eval-mlogloss:0.22536
[93]	train-mlogloss:0.27747	eval-mlogloss:0.22347
[94]	train-mlogloss:0.27533	eval-mlogloss:0.22144
[95]	train-mlogloss:0.27274	eval-mlogloss:0.21863
[96]	train-mlogloss:0.27145	eval-mlogloss:0.21724
[97]	train-mlogloss:0.27082	eval-mlogloss:0.21685
[98]	train-mlogloss:0.26889	eval-mlogloss:0.21442
[99]	train-mlogloss:0.26869	eval-mlogloss:0.21426
[100]	train-mlogloss:0.26736	eval-mlogloss:0.21287
[101]	train-mlogloss:0.26572	eval-mlogloss:0.21131
[102]	train-mlogloss:0.26542	eval-mlogloss:0.21106
[103]	train-mlogloss:0.26395	eval-mlogloss:0.20897
[104]	train-mlogloss:0.26270	eval-mlogloss:0.20712
[105]	train-mlogloss:0.26060	eval-mlogloss:0.20460
[106]	train-mlogloss:0.25889	eval-mlogloss:0.20253
[107]	train-mlogloss:0.25849	eval-mlogloss:0.20205
[108]	train-mlogloss:0.25836	eval-mlogloss:0.20201
[109]	train-mlogloss:0.25709	eval-mlogloss:0.20060
[110]	train-mlogloss:0.25583	eval-mlogloss:0.19906
[111]	train-mlogloss:0.25461	eval-mlogloss:0.19758
[112]	train-mlogloss:0.25315	eval-mlogloss:0.19562
[113]	train-mlogloss:0.25278	eval-mlogloss:0.19520
[114]	train-mlogloss:0.25159	eval-mlogloss:0.19354
[115]	train-mlogloss:0.25035	eval-mlogloss:0.19205
[116]	train-mlogloss:0.25028	eval-mlogloss:0.19195
[117]	train-mlogloss:0.24870	eval-mlogloss:0.19036
[118]	train-mlogloss:0.24868	eval-mlogloss:0.19043
[119]	train-mlogloss:0.24652	eval-mlogloss:0.18819
[120]	train-mlogloss:0.24629	eval-mlogloss:0.18789
[121]	train-mlogloss:0.24405	eval-mlogloss:0.18559
[122]	train-mlogloss:0.24387	eval-mlogloss:0.18534
[123]	train-mlogloss:0.24371	eval-mlogloss:0.18538
[124]	train-mlogloss:0.24253	eval-mlogloss:0.18393
[125]	train-mlogloss:0.24248	eval-mlogloss:0.18390
[126]	train-mlogloss:0.24142	eval-mlogloss:0.18258
[127]	train-mlogloss:0.24110	eval-mlogloss:0.18208
[128]	train-mlogloss:0.24095	eval-mlogloss:0.18188
[129]	train-mlogloss:0.23979	eval-mlogloss:0.18061
[130]	train-mlogloss:0.23980	eval-mlogloss:0.18062
[131]	train-mlogloss:0.23981	eval-mlogloss:0.18064
[132]	train-mlogloss:0.23944	eval-mlogloss:0.18023
[133]	train-mlogloss:0.23935	eval-mlogloss:0.18023
[134]	train-mlogloss:0.23922	eval-mlogloss:0.18016
[135]	train-mlogloss:0.23811	eval-mlogloss:0.17871
[136]	train-mlogloss:0.23801	eval-mlogloss:0.17864
[137]	train-mlogloss:0.23564	eval-mlogloss:0.17576
[138]	train-mlogloss:0.23554	eval-mlogloss:0.17573
[139]	train-mlogloss:0.23541	eval-mlogloss:0.17552
[140]	train-mlogloss:0.23527	eval-mlogloss:0.17535
[141]	train-mlogloss:0.23516	eval-mlogloss:0.17531
[142]	train-mlogloss:0.23513	eval-mlogloss:0.17523
[143]	train-mlogloss:0.23514	eval-mlogloss:0.17524
[144]	train-mlogloss:0.23508	eval-mlogloss:0.17504
[145]	train-mlogloss:0.23505	eval-mlogloss:0.17500
[146]	train-mlogloss:0.23501	eval-mlogloss:0.17495
[147]	train-mlogloss:0.23410	eval-mlogloss:0.17393
[148]	train-mlogloss:0.23294	eval-mlogloss:0.17268
[149]	train-mlogloss:0.23281	eval-mlogloss:0.17257
[150]	train-mlogloss:0.23279	eval-mlogloss:0.17259
[151]	train-mlogloss:0.23220	eval-mlogloss:0.17186
[152]	train-mlogloss:0.23222	eval-mlogloss:0.17178
[153]	train-mlogloss:0.23116	eval-mlogloss:0.17061
[154]	train-mlogloss:0.22977	eval-mlogloss:0.16903
[155]	train-mlogloss:0.22981	eval-mlogloss:0.16907
[156]	train-mlogloss:0.22925	eval-mlogloss:0.16826
[157]	train-mlogloss:0.22917	eval-mlogloss:0.16817
[158]	train-mlogloss:0.22909	eval-mlogloss:0.16807
[159]	train-mlogloss:0.22893	eval-mlogloss:0.16793
[160]	train-mlogloss:0.22879	eval-mlogloss:0.16784
[161]	train-mlogloss:0.22874	eval-mlogloss:0.16759
[162]	train-mlogloss:0.22871	eval-mlogloss:0.16764
[163]	train-mlogloss:0.22864	eval-mlogloss:0.16762
[164]	train-mlogloss:0.22859	eval-mlogloss:0.16756
[165]	train-mlogloss:0.22845	eval-mlogloss:0.16778
[166]	train-mlogloss:0.22826	eval-mlogloss:0.16753
[167]	train-mlogloss:0.22810	eval-mlogloss:0.16753
[168]	train-mlogloss:0.22796	eval-mlogloss:0.16732
[169]	train-mlogloss:0.22782	eval-mlogloss:0.16714
[170]	train-mlogloss:0.22777	eval-mlogloss:0.16725
[171]	train-mlogloss:0.22765	eval-mlogloss:0.16710
[172]	train-mlogloss:0.22759	eval-mlogloss:0.16698
[173]	train-mlogloss:0.22750	eval-mlogloss:0.16690
[174]	train-mlogloss:0.22726	eval-mlogloss:0.16656
[175]	train-mlogloss:0.22721	eval-mlogloss:0.16647
[176]	train-mlogloss:0.22702	eval-mlogloss:0.16631
[177]	train-mlogloss:0.22670	eval-mlogloss:0.16586
[178]	train-mlogloss:0.22572	eval-mlogloss:0.16463
[179]	train-mlogloss:0.22497	eval-mlogloss:0.16361
[180]	train-mlogloss:0.22494	eval-mlogloss:0.16350
[181]	train-mlogloss:0.22493	eval-mlogloss:0.16350
[182]	train-mlogloss:0.22491	eval-mlogloss:0.16351
[183]	train-mlogloss:0.22492	eval-mlogloss:0.16348
[184]	train-mlogloss:0.22478	eval-mlogloss:0.16347
[185]	train-mlogloss:0.22478	eval-mlogloss:0.16347
[186]	train-mlogloss:0.22470	eval-mlogloss:0.16347
[187]	train-mlogloss:0.22469	eval-mlogloss:0.16345
[188]	train-mlogloss:0.22468	eval-mlogloss:0.16331
[189]	train-mlogloss:0.22468	eval-mlogloss:0.16336
[190]	train-mlogloss:0.22469	eval-mlogloss:0.16345
[191]	train-mlogloss:0.22463	eval-mlogloss:0.16319
[192]	train-mlogloss:0.22461	eval-mlogloss:0.16325
[193]	train-mlogloss:0.22454	eval-mlogloss:0.16296
[194]	train-mlogloss:0.22440	eval-mlogloss:0.16281
[195]	train-mlogloss:0.22439	eval-mlogloss:0.16278
[196]	train-mlogloss:0.22422	eval-mlogloss:0.16261
[197]	train-mlogloss:0.22421	eval-mlogloss:0.16260
[198]	train-mlogloss:0.22416	eval-mlogloss:0.16267
[199]	train-mlogloss:0.22407	eval-mlogloss:0.16233
[200]	train-mlogloss:0.22407	eval-mlogloss:0.16232
[201]	train-mlogloss:0.22397	eval-mlogloss:0.16217
[202]	train-mlogloss:0.22397	eval-mlogloss:0.16219
[203]	train-mlogloss:0.22335	eval-mlogloss:0.16150
[204]	train-mlogloss:0.22320	eval-mlogloss:0.16134
[205]	train-mlogloss:0.22320	eval-mlogloss:0.16133
[206]	train-mlogloss:0.22319	eval-mlogloss:0.16139
[207]	train-mlogloss:0.22317	eval-mlogloss:0.16136
[208]	train-mlogloss:0.22313	eval-mlogloss:0.16141
[209]	train-mlogloss:0.22239	eval-mlogloss:0.16033
[210]	train-mlogloss:0.22231	eval-mlogloss:0.16025
[211]	train-mlogloss:0.22215	eval-mlogloss:0.16010
[212]	train-mlogloss:0.22211	eval-mlogloss:0.15975
[213]	train-mlogloss:0.22210	eval-mlogloss:0.15979
[214]	train-mlogloss:0.22210	eval-mlogloss:0.15977
[215]	train-mlogloss:0.22199	eval-mlogloss:0.15948
[216]	train-mlogloss:0.22182	eval-mlogloss:0.15919
[217]	train-mlogloss:0.22182	eval-mlogloss:0.15919
[218]	train-mlogloss:0.22112	eval-mlogloss:0.15823
[219]	train-mlogloss:0.22113	eval-mlogloss:0.15820
[220]	train-mlogloss:0.22105	eval-mlogloss:0.15814
[221]	train-mlogloss:0.22092	eval-mlogloss:0.15798
[222]	train-mlogloss:0.22089	eval-mlogloss:0.15796
[223]	train-mlogloss:0.22088	eval-mlogloss:0.15800
[224]	train-mlogloss:0.22078	eval-mlogloss:0.15781
[225]	train-mlogloss:0.22063	eval-mlogloss:0.15795
[226]	train-mlogloss:0.22066	eval-mlogloss:0.15795
[227]	train-mlogloss:0.22052	eval-mlogloss:0.15784
[228]	train-mlogloss:0.22049	eval-mlogloss:0.15784
[229]	train-mlogloss:0.22018	eval-mlogloss:0.15751
[230]	train-mlogloss:0.22016	eval-mlogloss:0.15757
[231]	train-mlogloss:0.22014	eval-mlogloss:0.15752
[232]	train-mlogloss:0.22008	eval-mlogloss:0.15751
[233]	train-mlogloss:0.22003	eval-mlogloss:0.15748
[234]	train-mlogloss:0.21997	eval-mlogloss:0.15754
[235]	train-mlogloss:0.21988	eval-mlogloss:0.15764
[236]	train-mlogloss:0.21988	eval-mlogloss:0.15768
[237]	train-mlogloss:0.21988	eval-mlogloss:0.15772
[238]	train-mlogloss:0.21972	eval-mlogloss:0.15762
[239]	train-mlogloss:0.21971	eval-mlogloss:0.15764
[240]	train-mlogloss:0.21961	eval-mlogloss:0.15753
[241]	train-mlogloss:0.21961	eval-mlogloss:0.15752
[242]	train-mlogloss:0.21961	eval-mlogloss:0.15753
[243]	train-mlogloss:0.21960	eval-mlogloss:0.15753
[244]	train-mlogloss:0.21959	eval-mlogloss:0.15753
[245]	train-mlogloss:0.21959	eval-mlogloss:0.15752
[246]	train-mlogloss:0.21958	eval-mlogloss:0.15746
[247]	train-mlogloss:0.21952	eval-mlogloss:0.15738
[248]	train-mlogloss:0.21952	eval-mlogloss:0.15739
[249]	train-mlogloss:0.21854	eval-mlogloss:0.15623
[250]	train-mlogloss:0.21843	eval-mlogloss:0.15575
[251]	train-mlogloss:0.21833	eval-mlogloss:0.15570
[252]	train-mlogloss:0.21833	eval-mlogloss:0.15566
[253]	train-mlogloss:0.21833	eval-mlogloss:0.15569
[254]	train-mlogloss:0.21833	eval-mlogloss:0.15570
[255]	train-mlogloss:0.21833	eval-mlogloss:0.15570
[256]	train-mlogloss:0.21821	eval-mlogloss:0.15551
[257]	train-mlogloss:0.21818	eval-mlogloss:0.15558
[258]	train-mlogloss:0.21818	eval-mlogloss:0.15556
[259]	train-mlogloss:0.21818	eval-mlogloss:0.15557
[260]	train-mlogloss:0.21818	eval-mlogloss:0.15559
[261]	train-mlogloss:0.21814	eval-mlogloss:0.15566
[262]	train-mlogloss:0.21807	eval-mlogloss:0.15559
[263]	train-mlogloss:0.21803	eval-mlogloss:0.15562
[264]	train-mlogloss:0.21803	eval-mlogloss:0.15562
[265]	train-mlogloss:0.21803	eval-mlogloss:0.15563
[266]	train-mlogloss:0.21803	eval-mlogloss:0.15567
[267]	train-mlogloss:0.21803	eval-mlogloss:0.15569
[268]	train-mlogloss:0.21785	eval-mlogloss:0.15571
[269]	train-mlogloss:0.21776	eval-mlogloss:0.15563
[270]	train-mlogloss:0.21706	eval-mlogloss:0.15460
[271]	train-mlogloss:0.21706	eval-mlogloss:0.15461
[272]	train-mlogloss:0.21707	eval-mlogloss:0.15460
[273]	train-mlogloss:0.21707	eval-mlogloss:0.15459
[274]	train-mlogloss:0.21702	eval-mlogloss:0.15470
[275]	train-mlogloss:0.21701	eval-mlogloss:0.15449
[276]	train-mlogloss:0.21701	eval-mlogloss:0.15443
[277]	train-mlogloss:0.21701	eval-mlogloss:0.15444
[278]	train-mlogloss:0.21701	eval-mlogloss:0.15441
[279]	train-mlogloss:0.21693	eval-mlogloss:0.15426
[280]	train-mlogloss:0.21613	eval-mlogloss:0.15308
[281]	train-mlogloss:0.21601	eval-mlogloss:0.15298
[282]	train-mlogloss:0.21601	eval-mlogloss:0.15293
[283]	train-mlogloss:0.21600	eval-mlogloss:0.15301
[284]	train-mlogloss:0.21598	eval-mlogloss:0.15294
[285]	train-mlogloss:0.21598	eval-mlogloss:0.15291
[286]	train-mlogloss:0.21598	eval-mlogloss:0.15294
[287]	train-mlogloss:0.21598	eval-mlogloss:0.15290
[288]	train-mlogloss:0.21598	eval-mlogloss:0.15292
[289]	train-mlogloss:0.21531	eval-mlogloss:0.15207
[290]	train-mlogloss:0.21522	eval-mlogloss:0.15199
[291]	train-mlogloss:0.21445	eval-mlogloss:0.15104
[292]	train-mlogloss:0.21444	eval-mlogloss:0.15099
[293]	train-mlogloss:0.21445	eval-mlogloss:0.15097
[294]	train-mlogloss:0.21444	eval-mlogloss:0.15100
[295]	train-mlogloss:0.21435	eval-mlogloss:0.15087
[296]	train-mlogloss:0.21435	eval-mlogloss:0.15093
[297]	train-mlogloss:0.21434	eval-mlogloss:0.15099
[298]	train-mlogloss:0.21430	eval-mlogloss:0.15090
[299]	train-mlogloss:0.21429	eval-mlogloss:0.15090

[I 2026-07-19 09:04:08,900] Trial 0 finished with value: 1.0 and parameters: {'lambda': 0.1768922998962018, 'alpha': 0.030624106999035852, 'eta': 0.03152436890744786, 'gamma': 0.07440134925912152, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.6218678294078834, 'colsample_bytree': 0.43426403773185257}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.06501	eval-mlogloss:1.06509
[1]	train-mlogloss:1.04809	eval-mlogloss:1.04703
[2]	train-mlogloss:1.02740	eval-mlogloss:1.02732
[3]	train-mlogloss:0.99178	eval-mlogloss:0.98905
[4]	train-mlogloss:0.97790	eval-mlogloss:0.97433
[5]	train-mlogloss:0.95556	eval-mlogloss:0.95276
[6]	train-mlogloss:0.92342	eval-mlogloss:0.91819
[7]	train-mlogloss:0.88937	eval-mlogloss:0.88111
[8]	train-mlogloss:0.87433	eval-mlogloss:0.86734
[9]	train-mlogloss:0.84285	eval-mlogloss:0.83441
[10]	train-mlogloss:0.81947	eval-mlogloss:0.80952
[11]	train-mlogloss:0.80898	eval-mlogloss:0.79880
[12]	train-mlogloss:0.78545	eval-mlogloss:0.77419
[13]	train-mlogloss:0.76602	eval-mlogloss:0.75407
[14]	train-mlogloss:0.73972	eval-mlogloss:0.72516
[15]	train-mlogloss:0.72495	eval-mlogloss:0.71011
[16]	train-mlogloss:0.71369	eval-mlogloss:0.69700
[17]	train-mlogloss:0.69529	eval-mlogloss:0.67886
[18]	train-mlogloss:0.67636	eval-mlogloss:0.65847
[19]	train-mlogloss:0.67155	eval-mlogloss:0.65376
[20]	train-mlogloss:0.66655	eval-mlogloss:0.64927
[21]	train-mlogloss:0.65133	eval-mlogloss:0.63403
[22]	train-mlogloss:0.63050	eval-mlogloss:0.61099
[23]	train-mlogloss:0.61027	eval-mlogloss:0.58937
[24]	train-mlogloss:0.59475	eval-mlogloss:0.57253
[25]	train-mlogloss:0.57629	eval-mlogloss:0.55206
[26]	train-mlogloss:0.57289	eval-mlogloss:0.54887
[27]	train-mlogloss:0.55685	eval-mlogloss:0.53094
[28]	train-mlogloss:0.54796	eval-mlogloss:0.52276
[29]	train-mlogloss:0.53830	eval-mlogloss:0.51231
[30]	train-mlogloss:0.53126	eval-mlogloss:0.50567
[31]	train-mlogloss:0.51951	eval-mlogloss:0.49265
[32]	train-mlogloss:0.50414	eval-mlogloss:0.47603
[33]	train-mlogloss:0.50003	eval-mlogloss:0.47032
[34]	train-mlogloss:0.49103	eval-mlogloss:0.46065
[35]	train-mlogloss:0.48132	eval-mlogloss:0.45062
[36]	train-mlogloss:0.47376	eval-mlogloss:0.44342
[37]	train-mlogloss:0.46024	eval-mlogloss:0.42885
[38]	train-mlogloss:0.45271	eval-mlogloss:0.42039
[39]	train-mlogloss:0.44350	eval-mlogloss:0.41061
[40]	train-mlogloss:0.43658	eval-mlogloss:0.40381
[41]	train-mlogloss:0.42795	eval-mlogloss:0.39395
[42]	train-mlogloss:0.42024	eval-mlogloss:0.38444
[43]	train-mlogloss:0.41239	eval-mlogloss:0.37536
[44]	train-mlogloss:0.40455	eval-mlogloss:0.36719
[45]	train-mlogloss:0.39481	eval-mlogloss:0.35621
[46]	train-mlogloss:0.39206	eval-mlogloss:0.35368
[47]	train-mlogloss:0.38637	eval-mlogloss:0.34698
[48]	train-mlogloss:0.38014	eval-mlogloss:0.34076
[49]	train-mlogloss:0.37430	eval-mlogloss:0.33406
[50]	train-mlogloss:0.36701	eval-mlogloss:0.32508
[51]	train-mlogloss:0.36057	eval-mlogloss:0.31863
[52]	train-mlogloss:0.35618	eval-mlogloss:0.31421
[53]	train-mlogloss:0.34811	eval-mlogloss:0.30513
[54]	train-mlogloss:0.34431	eval-mlogloss:0.30065
[55]	train-mlogloss:0.34333	eval-mlogloss:0.29982
[56]	train-mlogloss:0.34003	eval-mlogloss:0.29577
[57]	train-mlogloss:0.33518	eval-mlogloss:0.29084
[58]	train-mlogloss:0.32949	eval-mlogloss:0.28482
[59]	train-mlogloss:0.32265	eval-mlogloss:0.27733
[60]	train-mlogloss:0.31839	eval-mlogloss:0.27262
[61]	train-mlogloss:0.31553	eval-mlogloss:0.26972
[62]	train-mlogloss:0.31045	eval-mlogloss:0.26410
[63]	train-mlogloss:0.30769	eval-mlogloss:0.26103
[64]	train-mlogloss:0.30385	eval-mlogloss:0.25667
[65]	train-mlogloss:0.30110	eval-mlogloss:0.25350
[66]	train-mlogloss:0.29517	eval-mlogloss:0.24678
[67]	train-mlogloss:0.29246	eval-mlogloss:0.24391
[68]	train-mlogloss:0.28852	eval-mlogloss:0.23968
[69]	train-mlogloss:0.28727	eval-mlogloss:0.23851
[70]	train-mlogloss:0.28620	eval-mlogloss:0.23727
[71]	train-mlogloss:0.28114	eval-mlogloss:0.23145
[72]	train-mlogloss:0.28057	eval-mlogloss:0.23098
[73]	train-mlogloss:0.27862	eval-mlogloss:0.22911
[74]	train-mlogloss:0.27429	eval-mlogloss:0.22451
[75]	train-mlogloss:0.27249	eval-mlogloss:0.22250
[76]	train-mlogloss:0.27158	eval-mlogloss:0.22139
[77]	train-mlogloss:0.26803	eval-mlogloss:0.21750
[78]	train-mlogloss:0.26618	eval-mlogloss:0.21574
[79]	train-mlogloss:0.26308	eval-mlogloss:0.21196
[80]	train-mlogloss:0.26201	eval-mlogloss:0.21088
[81]	train-mlogloss:0.26178	eval-mlogloss:0.21056
[82]	train-mlogloss:0.26104	eval-mlogloss:0.20985
[83]	train-mlogloss:0.26082	eval-mlogloss:0.20983
[84]	train-mlogloss:0.25899	eval-mlogloss:0.20790
[85]	train-mlogloss:0.25806	eval-mlogloss:0.20690
[86]	train-mlogloss:0.25609	eval-mlogloss:0.20438
[87]	train-mlogloss:0.25442	eval-mlogloss:0.20214
[88]	train-mlogloss:0.25301	eval-mlogloss:0.20089
[89]	train-mlogloss:0.25232	eval-mlogloss:0.20029
[90]	train-mlogloss:0.25217	eval-mlogloss:0.20035
[91]	train-mlogloss:0.25200	eval-mlogloss:0.20030
[92]	train-mlogloss:0.25163	eval-mlogloss:0.19983
[93]	train-mlogloss:0.25006	eval-mlogloss:0.19812
[94]	train-mlogloss:0.24781	eval-mlogloss:0.19562
[95]	train-mlogloss:0.24621	eval-mlogloss:0.19393
[96]	train-mlogloss:0.24469	eval-mlogloss:0.19226
[97]	train-mlogloss:0.24437	eval-mlogloss:0.19233
[98]	train-mlogloss:0.24296	eval-mlogloss:0.19082
[99]	train-mlogloss:0.24280	eval-mlogloss:0.19058
[100]	train-mlogloss:0.24280	eval-mlogloss:0.19057
[101]	train-mlogloss:0.24261	eval-mlogloss:0.19058
[102]	train-mlogloss:0.24211	eval-mlogloss:0.19033
[103]	train-mlogloss:0.24071	eval-mlogloss:0.18831
[104]	train-mlogloss:0.23916	eval-mlogloss:0.18661
[105]	train-mlogloss:0.23751	eval-mlogloss:0.18447
[106]	train-mlogloss:0.23590	eval-mlogloss:0.18278
[107]	train-mlogloss:0.23546	eval-mlogloss:0.18227
[108]	train-mlogloss:0.23515	eval-mlogloss:0.18198
[109]	train-mlogloss:0.23383	eval-mlogloss:0.18058
[110]	train-mlogloss:0.23262	eval-mlogloss:0.17899
[111]	train-mlogloss:0.23132	eval-mlogloss:0.17723
[112]	train-mlogloss:0.23015	eval-mlogloss:0.17553
[113]	train-mlogloss:0.22986	eval-mlogloss:0.17509
[114]	train-mlogloss:0.22881	eval-mlogloss:0.17374
[115]	train-mlogloss:0.22754	eval-mlogloss:0.17203
[116]	train-mlogloss:0.22732	eval-mlogloss:0.17169
[117]	train-mlogloss:0.22624	eval-mlogloss:0.17045
[118]	train-mlogloss:0.22615	eval-mlogloss:0.17042
[119]	train-mlogloss:0.22494	eval-mlogloss:0.16915
[120]	train-mlogloss:0.22468	eval-mlogloss:0.16881
[121]	train-mlogloss:0.22357	eval-mlogloss:0.16731
[122]	train-mlogloss:0.22330	eval-mlogloss:0.16673
[123]	train-mlogloss:0.22323	eval-mlogloss:0.16686
[124]	train-mlogloss:0.22212	eval-mlogloss:0.16548
[125]	train-mlogloss:0.22198	eval-mlogloss:0.16537
[126]	train-mlogloss:0.22099	eval-mlogloss:0.16394
[127]	train-mlogloss:0.22080	eval-mlogloss:0.16376
[128]	train-mlogloss:0.21959	eval-mlogloss:0.16230
[129]	train-mlogloss:0.21853	eval-mlogloss:0.16100
[130]	train-mlogloss:0.21765	eval-mlogloss:0.15975
[131]	train-mlogloss:0.21759	eval-mlogloss:0.15944
[132]	train-mlogloss:0.21740	eval-mlogloss:0.15921
[133]	train-mlogloss:0.21713	eval-mlogloss:0.15928
[134]	train-mlogloss:0.21597	eval-mlogloss:0.15783
[135]	train-mlogloss:0.21500	eval-mlogloss:0.15654
[136]	train-mlogloss:0.21405	eval-mlogloss:0.15537
[137]	train-mlogloss:0.21400	eval-mlogloss:0.15506
[138]	train-mlogloss:0.21399	eval-mlogloss:0.15508
[139]	train-mlogloss:0.21380	eval-mlogloss:0.15510
[140]	train-mlogloss:0.21366	eval-mlogloss:0.15497
[141]	train-mlogloss:0.21347	eval-mlogloss:0.15481
[142]	train-mlogloss:0.21343	eval-mlogloss:0.15456
[143]	train-mlogloss:0.21332	eval-mlogloss:0.15469
[144]	train-mlogloss:0.21327	eval-mlogloss:0.15441
[145]	train-mlogloss:0.21299	eval-mlogloss:0.15411
[146]	train-mlogloss:0.21296	eval-mlogloss:0.15409
[147]	train-mlogloss:0.21288	eval-mlogloss:0.15401
[148]	train-mlogloss:0.21285	eval-mlogloss:0.15401
[149]	train-mlogloss:0.21272	eval-mlogloss:0.15386
[150]	train-mlogloss:0.21251	eval-mlogloss:0.15354
[151]	train-mlogloss:0.21248	eval-mlogloss:0.15348
[152]	train-mlogloss:0.21160	eval-mlogloss:0.15229
[153]	train-mlogloss:0.21147	eval-mlogloss:0.15214
[154]	train-mlogloss:0.21049	eval-mlogloss:0.15087
[155]	train-mlogloss:0.21040	eval-mlogloss:0.15076
[156]	train-mlogloss:0.20975	eval-mlogloss:0.14989
[157]	train-mlogloss:0.20971	eval-mlogloss:0.14980
[158]	train-mlogloss:0.20967	eval-mlogloss:0.14971
[159]	train-mlogloss:0.20951	eval-mlogloss:0.14954
[160]	train-mlogloss:0.20937	eval-mlogloss:0.14936
[161]	train-mlogloss:0.20938	eval-mlogloss:0.14936
[162]	train-mlogloss:0.20923	eval-mlogloss:0.14914
[163]	train-mlogloss:0.20905	eval-mlogloss:0.14917
[164]	train-mlogloss:0.20906	eval-mlogloss:0.14916
[165]	train-mlogloss:0.20887	eval-mlogloss:0.14915
[166]	train-mlogloss:0.20871	eval-mlogloss:0.14894
[167]	train-mlogloss:0.20868	eval-mlogloss:0.14902
[168]	train-mlogloss:0.20868	eval-mlogloss:0.14900
[169]	train-mlogloss:0.20857	eval-mlogloss:0.14885
[170]	train-mlogloss:0.20853	eval-mlogloss:0.14894
[171]	train-mlogloss:0.20831	eval-mlogloss:0.14860
[172]	train-mlogloss:0.20823	eval-mlogloss:0.14851
[173]	train-mlogloss:0.20810	eval-mlogloss:0.14841
[174]	train-mlogloss:0.20810	eval-mlogloss:0.14842
[175]	train-mlogloss:0.20797	eval-mlogloss:0.14831
[176]	train-mlogloss:0.20783	eval-mlogloss:0.14817
[177]	train-mlogloss:0.20776	eval-mlogloss:0.14807
[178]	train-mlogloss:0.20710	eval-mlogloss:0.14720
[179]	train-mlogloss:0.20707	eval-mlogloss:0.14719
[180]	train-mlogloss:0.20708	eval-mlogloss:0.14718
[181]	train-mlogloss:0.20703	eval-mlogloss:0.14730
[182]	train-mlogloss:0.20701	eval-mlogloss:0.14715
[183]	train-mlogloss:0.20694	eval-mlogloss:0.14718
[184]	train-mlogloss:0.20687	eval-mlogloss:0.14718
[185]	train-mlogloss:0.20686	eval-mlogloss:0.14720
[186]	train-mlogloss:0.20675	eval-mlogloss:0.14707
[187]	train-mlogloss:0.20672	eval-mlogloss:0.14688
[188]	train-mlogloss:0.20668	eval-mlogloss:0.14664
[189]	train-mlogloss:0.20662	eval-mlogloss:0.14659
[190]	train-mlogloss:0.20654	eval-mlogloss:0.14655
[191]	train-mlogloss:0.20650	eval-mlogloss:0.14631
[192]	train-mlogloss:0.20647	eval-mlogloss:0.14639
[193]	train-mlogloss:0.20645	eval-mlogloss:0.14623
[194]	train-mlogloss:0.20644	eval-mlogloss:0.14626
[195]	train-mlogloss:0.20642	eval-mlogloss:0.14626
[196]	train-mlogloss:0.20636	eval-mlogloss:0.14627
[197]	train-mlogloss:0.20626	eval-mlogloss:0.14619
[198]	train-mlogloss:0.20621	eval-mlogloss:0.14620
[199]	train-mlogloss:0.20618	eval-mlogloss:0.14603
[200]	train-mlogloss:0.20615	eval-mlogloss:0.14581
[201]	train-mlogloss:0.20609	eval-mlogloss:0.14576
[202]	train-mlogloss:0.20609	eval-mlogloss:0.14576
[203]	train-mlogloss:0.20609	eval-mlogloss:0.14579
[204]	train-mlogloss:0.20600	eval-mlogloss:0.14571
[205]	train-mlogloss:0.20600	eval-mlogloss:0.14571
[206]	train-mlogloss:0.20595	eval-mlogloss:0.14569
[207]	train-mlogloss:0.20585	eval-mlogloss:0.14557
[208]	train-mlogloss:0.20585	eval-mlogloss:0.14560
[209]	train-mlogloss:0.20585	eval-mlogloss:0.14561
[210]	train-mlogloss:0.20577	eval-mlogloss:0.14551
[211]	train-mlogloss:0.20572	eval-mlogloss:0.14552
[212]	train-mlogloss:0.20570	eval-mlogloss:0.14537
[213]	train-mlogloss:0.20570	eval-mlogloss:0.14539
[214]	train-mlogloss:0.20570	eval-mlogloss:0.14539
[215]	train-mlogloss:0.20556	eval-mlogloss:0.14518
[216]	train-mlogloss:0.20536	eval-mlogloss:0.14484
[217]	train-mlogloss:0.20533	eval-mlogloss:0.14456
[218]	train-mlogloss:0.20450	eval-mlogloss:0.14340
[219]	train-mlogloss:0.20450	eval-mlogloss:0.14341
[220]	train-mlogloss:0.20446	eval-mlogloss:0.14343
[221]	train-mlogloss:0.20446	eval-mlogloss:0.14345
[222]	train-mlogloss:0.20365	eval-mlogloss:0.14233
[223]	train-mlogloss:0.20363	eval-mlogloss:0.14233
[224]	train-mlogloss:0.20363	eval-mlogloss:0.14235
[225]	train-mlogloss:0.20363	eval-mlogloss:0.14237
[226]	train-mlogloss:0.20345	eval-mlogloss:0.14237
[227]	train-mlogloss:0.20275	eval-mlogloss:0.14147
[228]	train-mlogloss:0.20262	eval-mlogloss:0.14127
[229]	train-mlogloss:0.20250	eval-mlogloss:0.14116
[230]	train-mlogloss:0.20247	eval-mlogloss:0.14115
[231]	train-mlogloss:0.20247	eval-mlogloss:0.14117
[232]	train-mlogloss:0.20247	eval-mlogloss:0.14118
[233]	train-mlogloss:0.20247	eval-mlogloss:0.14120
[234]	train-mlogloss:0.20242	eval-mlogloss:0.14124
[235]	train-mlogloss:0.20240	eval-mlogloss:0.14130
[236]	train-mlogloss:0.20238	eval-mlogloss:0.14124
[237]	train-mlogloss:0.20232	eval-mlogloss:0.14117
[238]	train-mlogloss:0.20224	eval-mlogloss:0.14111
[239]	train-mlogloss:0.20222	eval-mlogloss:0.14109
[240]	train-mlogloss:0.20222	eval-mlogloss:0.14112
[241]	train-mlogloss:0.20222	eval-mlogloss:0.14113
[242]	train-mlogloss:0.20216	eval-mlogloss:0.14116
[243]	train-mlogloss:0.20214	eval-mlogloss:0.14114
[244]	train-mlogloss:0.20212	eval-mlogloss:0.14099
[245]	train-mlogloss:0.20140	eval-mlogloss:0.13997
[246]	train-mlogloss:0.20140	eval-mlogloss:0.13998
[247]	train-mlogloss:0.20062	eval-mlogloss:0.13889
[248]	train-mlogloss:0.20062	eval-mlogloss:0.13890
[249]	train-mlogloss:0.20058	eval-mlogloss:0.13890
[250]	train-mlogloss:0.20058	eval-mlogloss:0.13890
[251]	train-mlogloss:0.20052	eval-mlogloss:0.13885
[252]	train-mlogloss:0.20043	eval-mlogloss:0.13875
[253]	train-mlogloss:0.20043	eval-mlogloss:0.13876
[254]	train-mlogloss:0.20043	eval-mlogloss:0.13877
[255]	train-mlogloss:0.20043	eval-mlogloss:0.13876
[256]	train-mlogloss:0.20036	eval-mlogloss:0.13867
[257]	train-mlogloss:0.20034	eval-mlogloss:0.13871
[258]	train-mlogloss:0.20034	eval-mlogloss:0.13871
[259]	train-mlogloss:0.20034	eval-mlogloss:0.13872
[260]	train-mlogloss:0.20032	eval-mlogloss:0.13857
[261]	train-mlogloss:0.20032	eval-mlogloss:0.13859
[262]	train-mlogloss:0.20021	eval-mlogloss:0.13850
[263]	train-mlogloss:0.20021	eval-mlogloss:0.13854
[264]	train-mlogloss:0.20019	eval-mlogloss:0.13852
[265]	train-mlogloss:0.20019	eval-mlogloss:0.13851
[266]	train-mlogloss:0.20012	eval-mlogloss:0.13850
[267]	train-mlogloss:0.20012	eval-mlogloss:0.13851
[268]	train-mlogloss:0.20009	eval-mlogloss:0.13855
[269]	train-mlogloss:0.20001	eval-mlogloss:0.13845
[270]	train-mlogloss:0.19999	eval-mlogloss:0.13830
[271]	train-mlogloss:0.19942	eval-mlogloss:0.13753
[272]	train-mlogloss:0.19942	eval-mlogloss:0.13754
[273]	train-mlogloss:0.19934	eval-mlogloss:0.13741
[274]	train-mlogloss:0.19934	eval-mlogloss:0.13742
[275]	train-mlogloss:0.19933	eval-mlogloss:0.13736
[276]	train-mlogloss:0.19933	eval-mlogloss:0.13737
[277]	train-mlogloss:0.19928	eval-mlogloss:0.13739
[278]	train-mlogloss:0.19928	eval-mlogloss:0.13740
[279]	train-mlogloss:0.19919	eval-mlogloss:0.13731
[280]	train-mlogloss:0.19919	eval-mlogloss:0.13729
[281]	train-mlogloss:0.19914	eval-mlogloss:0.13722
[282]	train-mlogloss:0.19907	eval-mlogloss:0.13716
[283]	train-mlogloss:0.19905	eval-mlogloss:0.13704
[284]	train-mlogloss:0.19904	eval-mlogloss:0.13699
[285]	train-mlogloss:0.19901	eval-mlogloss:0.13676
[286]	train-mlogloss:0.19901	eval-mlogloss:0.13677
[287]	train-mlogloss:0.19901	eval-mlogloss:0.13678
[288]	train-mlogloss:0.19901	eval-mlogloss:0.13672
[289]	train-mlogloss:0.19901	eval-mlogloss:0.13673
[290]	train-mlogloss:0.19894	eval-mlogloss:0.13668
[291]	train-mlogloss:0.19894	eval-mlogloss:0.13667
[292]	train-mlogloss:0.19894	eval-mlogloss:0.13670
[293]	train-mlogloss:0.19888	eval-mlogloss:0.13666
[294]	train-mlogloss:0.19886	eval-mlogloss:0.13659
[295]	train-mlogloss:0.19879	eval-mlogloss:0.13652
[296]	train-mlogloss:0.19868	eval-mlogloss:0.13641
[297]	train-mlogloss:0.19868	eval-mlogloss:0.13648
[298]	train-mlogloss:0.19864	eval-mlogloss:0.13648
[299]	train-mlogloss:0.19860	eval-mlogloss:0.13656

[I 2026-07-19 09:04:11,144] Trial 1 finished with value: 1.0 and parameters: {'lambda': 2.2103251643439382e-07, 'alpha': 4.175424209513861e-08, 'eta': 0.03436484775445913, 'gamma': 0.07490304334488315, 'max_depth': 6, 'min_child_weight': 9, 'subsample': 0.8891669007431254, 'colsample_bytree': 0.4246211933340255}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.93939	eval-mlogloss:0.93350
[1]	train-mlogloss:0.86845	eval-mlogloss:0.86238

[I 2026-07-19 09:04:11,162] Trial 2 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.99816	eval-mlogloss:0.99888
[1]	train-mlogloss:0.94042	eval-mlogloss:0.94617

[I 2026-07-19 09:04:11,193] Trial 3 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.79302	eval-mlogloss:0.78653
[1]	train-mlogloss:0.60018	eval-mlogloss:0.57742

[I 2026-07-19 09:04:11,213] Trial 4 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.93571	eval-mlogloss:0.92806
[1]	train-mlogloss:0.87113	eval-mlogloss:0.85912

[I 2026-07-19 09:04:11,230] Trial 5 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05502	eval-mlogloss:1.05478
[1]	train-mlogloss:1.01519	eval-mlogloss:1.01238

[I 2026-07-19 09:04:11,246] Trial 6 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.01021	eval-mlogloss:1.00990
[1]	train-mlogloss:0.93283	eval-mlogloss:0.92680

[I 2026-07-19 09:04:11,263] Trial 7 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.00823	eval-mlogloss:1.00640
[1]	train-mlogloss:0.96205	eval-mlogloss:0.95399

[I 2026-07-19 09:04:11,318] Trial 8 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.96075	eval-mlogloss:0.95626
[1]	train-mlogloss:0.84743	eval-mlogloss:0.83366

[I 2026-07-19 09:04:11,340] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.86645	eval-mlogloss:0.85888
[1]	train-mlogloss:0.77919	eval-mlogloss:0.75509

[I 2026-07-19 09:04:11,478] Trial 10 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08430	eval-mlogloss:1.08549
[1]	train-mlogloss:1.07693	eval-mlogloss:1.07867
[2]	train-mlogloss:1.06777	eval-mlogloss:1.06994
[3]	train-mlogloss:1.05216	eval-mlogloss:1.05368
[4]	train-mlogloss:1.04550	eval-mlogloss:1.04630
[5]	train-mlogloss:1.03500	eval-mlogloss:1.03589
[6]	train-mlogloss:1.02022	eval-mlogloss:1.02004
[7]	train-mlogloss:1.00373	eval-mlogloss:1.00231
[8]	train-mlogloss:0.99573	eval-mlogloss:0.99538
[9]	train-mlogloss:0.97974	eval-mlogloss:0.97867
[10]	train-mlogloss:0.96736	eval-mlogloss:0.96579
[11]	train-mlogloss:0.96139	eval-mlogloss:0.96015
[12]	train-mlogloss:0.94865	eval-mlogloss:0.94684
[13]	train-mlogloss:0.93803	eval-mlogloss:0.93614
[14]	train-mlogloss:0.92343	eval-mlogloss:0.92037
[15]	train-mlogloss:0.91453	eval-mlogloss:0.91115
[16]	train-mlogloss:0.90796	eval-mlogloss:0.90383
[17]	train-mlogloss:0.89710	eval-mlogloss:0.89329
[18]	train-mlogloss:0.88579	eval-mlogloss:0.88104
[19]	train-mlogloss:0.88242	eval-mlogloss:0.87784
[20]	train-mlogloss:0.87912	eval-mlogloss:0.87468
[21]	train-mlogloss:0.86957	eval-mlogloss:0.86541
[22]	train-mlogloss:0.85646	eval-mlogloss:0.85118
[23]	train-mlogloss:0.84351	eval-mlogloss:0.83753
[24]	train-mlogloss:0.83319	eval-mlogloss:0.82632
[25]	train-mlogloss:0.82076	eval-mlogloss:0.81314
[26]	train-mlogloss:0.81785	eval-mlogloss:0.81035
[27]	train-mlogloss:0.80724	eval-mlogloss:0.79881
[28]	train-mlogloss:0.80074	eval-mlogloss:0.79286
[29]	train-mlogloss:0.79371	eval-mlogloss:0.78515
[30]	train-mlogloss:0.78830	eval-mlogloss:0.77986
[31]	train-mlogloss:0.77957	eval-mlogloss:0.77096
[32]	train-mlogloss:0.76825	eval-mlogloss:0.75892
[33]	train-mlogloss:0.76420	eval-mlogloss:0.75538
[34]	train-mlogloss:0.75722	eval-mlogloss:0.74790
[35]	train-mlogloss:0.74970	eval-mlogloss:0.74010
[36]	train-mlogloss:0.74318	eval-mlogloss:0.73361
[37]	train-mlogloss:0.73260	eval-mlogloss:0.72232
[38]	train-mlogloss:0.72544	eval-mlogloss:0.71487
[39]	train-mlogloss:0.71775	eval-mlogloss:0.70662
[40]	train-mlogloss:0.71198	eval-mlogloss:0.70087
[41]	train-mlogloss:0.70461	eval-mlogloss:0.69266
[42]	train-mlogloss:0.69695	eval-mlogloss:0.68449
[43]	train-mlogloss:0.68933	eval-mlogloss:0.67664
[44]	train-mlogloss:0.68203	eval-mlogloss:0.66943
[45]	train-mlogloss:0.67263	eval-mlogloss:0.65937
[46]	train-mlogloss:0.66955	eval-mlogloss:0.65683
[47]	train-mlogloss:0.66329	eval-mlogloss:0.64990
[48]	train-mlogloss:0.65705	eval-mlogloss:0.64357
[49]	train-mlogloss:0.65094	eval-mlogloss:0.63715
[50]	train-mlogloss:0.64326	eval-mlogloss:0.62865
[51]	train-mlogloss:0.63640	eval-mlogloss:0.62176
[52]	train-mlogloss:0.63186	eval-mlogloss:0.61711
[53]	train-mlogloss:0.62345	eval-mlogloss:0.60803
[54]	train-mlogloss:0.61876	eval-mlogloss:0.60311
[55]	train-mlogloss:0.61693	eval-mlogloss:0.60202
[56]	train-mlogloss:0.61218	eval-mlogloss:0.59691
[57]	train-mlogloss:0.60661	eval-mlogloss:0.59124
[58]	train-mlogloss:0.60057	eval-mlogloss:0.58522
[59]	train-mlogloss:0.59268	eval-mlogloss:0.57671
[60]	train-mlogloss:0.58654	eval-mlogloss:0.57024
[61]	train-mlogloss:0.58330	eval-mlogloss:0.56684
[62]	train-mlogloss:0.57669	eval-mlogloss:0.55973
[63]	train-mlogloss:0.57347	eval-mlogloss:0.55682
[64]	train-mlogloss:0.56846	eval-mlogloss:0.55149
[65]	train-mlogloss:0.56462	eval-mlogloss:0.54776
[66]	train-mlogloss:0.55746	eval-mlogloss:0.54004
[67]	train-mlogloss:0.55372	eval-mlogloss:0.53618
[68]	train-mlogloss:0.54849	eval-mlogloss:0.53052
[69]	train-mlogloss:0.54524	eval-mlogloss:0.52748
[70]	train-mlogloss:0.54314	eval-mlogloss:0.52533
[71]	train-mlogloss:0.53636	eval-mlogloss:0.51774
[72]	train-mlogloss:0.53497	eval-mlogloss:0.51692
[73]	train-mlogloss:0.53118	eval-mlogloss:0.51308
[74]	train-mlogloss:0.52448	eval-mlogloss:0.50600
[75]	train-mlogloss:0.52081	eval-mlogloss:0.50227
[76]	train-mlogloss:0.51888	eval-mlogloss:0.50078
[77]	train-mlogloss:0.51414	eval-mlogloss:0.49566
[78]	train-mlogloss:0.50986	eval-mlogloss:0.49105
[79]	train-mlogloss:0.50531	eval-mlogloss:0.48592
[80]	train-mlogloss:0.50355	eval-mlogloss:0.48409
[81]	train-mlogloss:0.50097	eval-mlogloss:0.48174
[82]	train-mlogloss:0.49682	eval-mlogloss:0.47747
[83]	train-mlogloss:0.49415	eval-mlogloss:0.47485
[84]	train-mlogloss:0.48975	eval-mlogloss:0.47007
[85]	train-mlogloss:0.48647	eval-mlogloss:0.46685
[86]	train-mlogloss:0.48343	eval-mlogloss:0.46415
[87]	train-mlogloss:0.47914	eval-mlogloss:0.45963
[88]	train-mlogloss:0.47593	eval-mlogloss:0.45635
[89]	train-mlogloss:0.47209	eval-mlogloss:0.45237
[90]	train-mlogloss:0.46985	eval-mlogloss:0.45000
[91]	train-mlogloss:0.46747	eval-mlogloss:0.44761
[92]	train-mlogloss:0.46536	eval-mlogloss:0.44524
[93]	train-mlogloss:0.46266	eval-mlogloss:0.44250
[94]	train-mlogloss:0.45713	eval-mlogloss:0.43662
[95]	train-mlogloss:0.45310	eval-mlogloss:0.43238
[96]	train-mlogloss:0.44922	eval-mlogloss:0.42815
[97]	train-mlogloss:0.44631	eval-mlogloss:0.42524
[98]	train-mlogloss:0.44236	eval-mlogloss:0.42105
[99]	train-mlogloss:0.44152	eval-mlogloss:0.42074
[100]	train-mlogloss:0.43942	eval-mlogloss:0.41888
[101]	train-mlogloss:0.43749	eval-mlogloss:0.41693
[102]	train-mlogloss:0.43416	eval-mlogloss:0.41344
[103]	train-mlogloss:0.43064	eval-mlogloss:0.40945
[104]	train-mlogloss:0.42696	eval-mlogloss:0.40573
[105]	train-mlogloss:0.42337	eval-mlogloss:0.40164
[106]	train-mlogloss:0.41907	eval-mlogloss:0.39705
[107]	train-mlogloss:0.41737	eval-mlogloss:0.39516
[108]	train-mlogloss:0.41425	eval-mlogloss:0.39189
[109]	train-mlogloss:0.41144	eval-mlogloss:0.38891
[110]	train-mlogloss:0.40937	eval-mlogloss:0.38659
[111]	train-mlogloss:0.40487	eval-mlogloss:0.38134
[112]	train-mlogloss:0.40227	eval-mlogloss:0.37834
[113]	train-mlogloss:0.39941	eval-mlogloss:0.37506
[114]	train-mlogloss:0.39633	eval-mlogloss:0.37154
[115]	train-mlogloss:0.39332	eval-mlogloss:0.36803
[116]	train-mlogloss:0.39173	eval-mlogloss:0.36637
[117]	train-mlogloss:0.38855	eval-mlogloss:0.36289
[118]	train-mlogloss:0.38797	eval-mlogloss:0.36261
[119]	train-mlogloss:0.38553	eval-mlogloss:0.35998
[120]	train-mlogloss:0.38226	eval-mlogloss:0.35632
[121]	train-mlogloss:0.37822	eval-mlogloss:0.35157
[122]	train-mlogloss:0.37623	eval-mlogloss:0.34946
[123]	train-mlogloss:0.37390	eval-mlogloss:0.34677
[124]	train-mlogloss:0.37153	eval-mlogloss:0.34425
[125]	train-mlogloss:0.37003	eval-mlogloss:0.34276
[126]	train-mlogloss:0.36720	eval-mlogloss:0.33974
[127]	train-mlogloss:0.36467	eval-mlogloss:0.33705
[128]	train-mlogloss:0.36143	eval-mlogloss:0.33331
[129]	train-mlogloss:0.35837	eval-mlogloss:0.32971
[130]	train-mlogloss:0.35480	eval-mlogloss:0.32581
[131]	train-mlogloss:0.35276	eval-mlogloss:0.32340
[132]	train-mlogloss:0.35014	eval-mlogloss:0.32060
[133]	train-mlogloss:0.34926	eval-mlogloss:0.31977
[134]	train-mlogloss:0.34681	eval-mlogloss:0.31689
[135]	train-mlogloss:0.34481	eval-mlogloss:0.31473
[136]	train-mlogloss:0.34241	eval-mlogloss:0.31191
[137]	train-mlogloss:0.34003	eval-mlogloss:0.30915
[138]	train-mlogloss:0.33740	eval-mlogloss:0.30604
[139]	train-mlogloss:0.33618	eval-mlogloss:0.30474
[140]	train-mlogloss:0.33437	eval-mlogloss:0.30255
[141]	train-mlogloss:0.33205	eval-mlogloss:0.29990
[142]	train-mlogloss:0.33052	eval-mlogloss:0.29836
[143]	train-mlogloss:0.32867	eval-mlogloss:0.29612
[144]	train-mlogloss:0.32646	eval-mlogloss:0.29354
[145]	train-mlogloss:0.32499	eval-mlogloss:0.29204
[146]	train-mlogloss:0.32212	eval-mlogloss:0.28867
[147]	train-mlogloss:0.32001	eval-mlogloss:0.28617
[148]	train-mlogloss:0.31798	eval-mlogloss:0.28384
[149]	train-mlogloss:0.31590	eval-mlogloss:0.28137
[150]	train-mlogloss:0.31466	eval-mlogloss:0.27996
[151]	train-mlogloss:0.31278	eval-mlogloss:0.27756
[152]	train-mlogloss:0.31004	eval-mlogloss:0.27439
[153]	train-mlogloss:0.30872	eval-mlogloss:0.27308
[154]	train-mlogloss:0.30639	eval-mlogloss:0.27055
[155]	train-mlogloss:0.30487	eval-mlogloss:0.26868
[156]	train-mlogloss:0.30309	eval-mlogloss:0.26642
[157]	train-mlogloss:0.30050	eval-mlogloss:0.26341
[158]	train-mlogloss:0.29794	eval-mlogloss:0.26045
[159]	train-mlogloss:0.29694	eval-mlogloss:0.25937
[160]	train-mlogloss:0.29665	eval-mlogloss:0.25909
[161]	train-mlogloss:0.29607	eval-mlogloss:0.25849
[162]	train-mlogloss:0.29416	eval-mlogloss:0.25650
[163]	train-mlogloss:0.29394	eval-mlogloss:0.25631
[164]	train-mlogloss:0.29160	eval-mlogloss:0.25333
[165]	train-mlogloss:0.29111	eval-mlogloss:0.25282
[166]	train-mlogloss:0.28938	eval-mlogloss:0.25066
[167]	train-mlogloss:0.28733	eval-mlogloss:0.24842
[168]	train-mlogloss:0.28555	eval-mlogloss:0.24643
[169]	train-mlogloss:0.28390	eval-mlogloss:0.24456
[170]	train-mlogloss:0.28192	eval-mlogloss:0.24240
[171]	train-mlogloss:0.28094	eval-mlogloss:0.24107
[172]	train-mlogloss:0.27932	eval-mlogloss:0.23914
[173]	train-mlogloss:0.27803	eval-mlogloss:0.23776
[174]	train-mlogloss:0.27684	eval-mlogloss:0.23617
[175]	train-mlogloss:0.27557	eval-mlogloss:0.23480
[176]	train-mlogloss:0.27475	eval-mlogloss:0.23395
[177]	train-mlogloss:0.27412	eval-mlogloss:0.23321
[178]	train-mlogloss:0.27243	eval-mlogloss:0.23097
[179]	train-mlogloss:0.27031	eval-mlogloss:0.22847
[180]	train-mlogloss:0.26822	eval-mlogloss:0.22601
[181]	train-mlogloss:0.26705	eval-mlogloss:0.22467
[182]	train-mlogloss:0.26589	eval-mlogloss:0.22342
[183]	train-mlogloss:0.26458	eval-mlogloss:0.22209
[184]	train-mlogloss:0.26329	eval-mlogloss:0.22078
[185]	train-mlogloss:0.26247	eval-mlogloss:0.21968
[186]	train-mlogloss:0.26209	eval-mlogloss:0.21928
[187]	train-mlogloss:0.26115	eval-mlogloss:0.21823
[188]	train-mlogloss:0.26041	eval-mlogloss:0.21746
[189]	train-mlogloss:0.25955	eval-mlogloss:0.21639
[190]	train-mlogloss:0.25851	eval-mlogloss:0.21510
[191]	train-mlogloss:0.25815	eval-mlogloss:0.21472
[192]	train-mlogloss:0.25691	eval-mlogloss:0.21347
[193]	train-mlogloss:0.25602	eval-mlogloss:0.21247
[194]	train-mlogloss:0.25524	eval-mlogloss:0.21142
[195]	train-mlogloss:0.25382	eval-mlogloss:0.20954
[196]	train-mlogloss:0.25241	eval-mlogloss:0.20786
[197]	train-mlogloss:0.25161	eval-mlogloss:0.20685
[198]	train-mlogloss:0.25069	eval-mlogloss:0.20582
[199]	train-mlogloss:0.24938	eval-mlogloss:0.20425
[200]	train-mlogloss:0.24863	eval-mlogloss:0.20358
[201]	train-mlogloss:0.24830	eval-mlogloss:0.20321
[202]	train-mlogloss:0.24746	eval-mlogloss:0.20234
[203]	train-mlogloss:0.24580	eval-mlogloss:0.20022
[204]	train-mlogloss:0.24498	eval-mlogloss:0.19930
[205]	train-mlogloss:0.24328	eval-mlogloss:0.19732
[206]	train-mlogloss:0.24205	eval-mlogloss:0.19584
[207]	train-mlogloss:0.24124	eval-mlogloss:0.19501
[208]	train-mlogloss:0.24076	eval-mlogloss:0.19441
[209]	train-mlogloss:0.23997	eval-mlogloss:0.19346
[210]	train-mlogloss:0.23982	eval-mlogloss:0.19340
[211]	train-mlogloss:0.23879	eval-mlogloss:0.19232
[212]	train-mlogloss:0.23792	eval-mlogloss:0.19124
[213]	train-mlogloss:0.23691	eval-mlogloss:0.18989
[214]	train-mlogloss:0.23535	eval-mlogloss:0.18812
[215]	train-mlogloss:0.23459	eval-mlogloss:0.18728
[216]	train-mlogloss:0.23346	eval-mlogloss:0.18605
[217]	train-mlogloss:0.23236	eval-mlogloss:0.18470
[218]	train-mlogloss:0.23148	eval-mlogloss:0.18364
[219]	train-mlogloss:0.23048	eval-mlogloss:0.18241
[220]	train-mlogloss:0.22933	eval-mlogloss:0.18103
[221]	train-mlogloss:0.22893	eval-mlogloss:0.18056
[222]	train-mlogloss:0.22811	eval-mlogloss:0.17965
[223]	train-mlogloss:0.22756	eval-mlogloss:0.17894
[224]	train-mlogloss:0.22649	eval-mlogloss:0.17763
[225]	train-mlogloss:0.22595	eval-mlogloss:0.17720
[226]	train-mlogloss:0.22595	eval-mlogloss:0.17721
[227]	train-mlogloss:0.22499	eval-mlogloss:0.17598
[228]	train-mlogloss:0.22451	eval-mlogloss:0.17542
[229]	train-mlogloss:0.22426	eval-mlogloss:0.17514
[230]	train-mlogloss:0.22341	eval-mlogloss:0.17422
[231]	train-mlogloss:0.22259	eval-mlogloss:0.17317
[232]	train-mlogloss:0.22259	eval-mlogloss:0.17318
[233]	train-mlogloss:0.22183	eval-mlogloss:0.17233
[234]	train-mlogloss:0.22105	eval-mlogloss:0.17124
[235]	train-mlogloss:0.22049	eval-mlogloss:0.17056
[236]	train-mlogloss:0.21966	eval-mlogloss:0.16958
[237]	train-mlogloss:0.21914	eval-mlogloss:0.16902
[238]	train-mlogloss:0.21903	eval-mlogloss:0.16886
[239]	train-mlogloss:0.21882	eval-mlogloss:0.16861
[240]	train-mlogloss:0.21851	eval-mlogloss:0.16820
[241]	train-mlogloss:0.21845	eval-mlogloss:0.16825
[242]	train-mlogloss:0.21818	eval-mlogloss:0.16804
[243]	train-mlogloss:0.21797	eval-mlogloss:0.16779
[244]	train-mlogloss:0.21753	eval-mlogloss:0.16717
[245]	train-mlogloss:0.21682	eval-mlogloss:0.16638
[246]	train-mlogloss:0.21682	eval-mlogloss:0.16638
[247]	train-mlogloss:0.21632	eval-mlogloss:0.16585
[248]	train-mlogloss:0.21564	eval-mlogloss:0.16496
[249]	train-mlogloss:0.21501	eval-mlogloss:0.16411
[250]	train-mlogloss:0.21491	eval-mlogloss:0.16397
[251]	train-mlogloss:0.21480	eval-mlogloss:0.16382
[252]	train-mlogloss:0.21437	eval-mlogloss:0.16322
[253]	train-mlogloss:0.21431	eval-mlogloss:0.16326
[254]	train-mlogloss:0.21388	eval-mlogloss:0.16267
[255]	train-mlogloss:0.21363	eval-mlogloss:0.16246
[256]	train-mlogloss:0.21315	eval-mlogloss:0.16195
[257]	train-mlogloss:0.21255	eval-mlogloss:0.16114
[258]	train-mlogloss:0.21208	eval-mlogloss:0.16064
[259]	train-mlogloss:0.21144	eval-mlogloss:0.15992
[260]	train-mlogloss:0.21103	eval-mlogloss:0.15936
[261]	train-mlogloss:0.21046	eval-mlogloss:0.15857
[262]	train-mlogloss:0.21040	eval-mlogloss:0.15862
[263]	train-mlogloss:0.20978	eval-mlogloss:0.15791
[264]	train-mlogloss:0.20921	eval-mlogloss:0.15714
[265]	train-mlogloss:0.20899	eval-mlogloss:0.15698
[266]	train-mlogloss:0.20860	eval-mlogloss:0.15643
[267]	train-mlogloss:0.20850	eval-mlogloss:0.15629
[268]	train-mlogloss:0.20790	eval-mlogloss:0.15562
[269]	train-mlogloss:0.20747	eval-mlogloss:0.15516
[270]	train-mlogloss:0.20704	eval-mlogloss:0.15470
[271]	train-mlogloss:0.20650	eval-mlogloss:0.15395
[272]	train-mlogloss:0.20592	eval-mlogloss:0.15329
[273]	train-mlogloss:0.20550	eval-mlogloss:0.15274
[274]	train-mlogloss:0.20494	eval-mlogloss:0.15211
[275]	train-mlogloss:0.20439	eval-mlogloss:0.15139
[276]	train-mlogloss:0.20432	eval-mlogloss:0.15143
[277]	train-mlogloss:0.20378	eval-mlogloss:0.15082
[278]	train-mlogloss:0.20372	eval-mlogloss:0.15086
[279]	train-mlogloss:0.20332	eval-mlogloss:0.15044
[280]	train-mlogloss:0.20293	eval-mlogloss:0.15001
[281]	train-mlogloss:0.20284	eval-mlogloss:0.14989
[282]	train-mlogloss:0.20248	eval-mlogloss:0.14939
[283]	train-mlogloss:0.20213	eval-mlogloss:0.14888
[284]	train-mlogloss:0.20193	eval-mlogloss:0.14875
[285]	train-mlogloss:0.20187	eval-mlogloss:0.14880
[286]	train-mlogloss:0.20152	eval-mlogloss:0.14830
[287]	train-mlogloss:0.20146	eval-mlogloss:0.14835
[288]	train-mlogloss:0.20098	eval-mlogloss:0.14768
[289]	train-mlogloss:0.20064	eval-mlogloss:0.14720
[290]	train-mlogloss:0.20030	eval-mlogloss:0.14672
[291]	train-mlogloss:0.19996	eval-mlogloss:0.14624
[292]	train-mlogloss:0.19984	eval-mlogloss:0.14608
[293]	train-mlogloss:0.19946	eval-mlogloss:0.14568
[294]	train-mlogloss:0.19926	eval-mlogloss:0.14541
[295]	train-mlogloss:0.19889	eval-mlogloss:0.14501
[296]	train-mlogloss:0.19882	eval-mlogloss:0.14506
[297]	train-mlogloss:0.19846	eval-mlogloss:0.14467
[298]	train-mlogloss:0.19801	eval-mlogloss:0.14406
[299]	train-mlogloss:0.19784	eval-mlogloss:0.14395

[I 2026-07-19 09:04:13,447] Trial 11 finished with value: 1.0 and parameters: {'lambda': 0.6232245854381271, 'alpha': 1.10122169795393e-08, 'eta': 0.014643910207646021, 'gamma': 0.5124828160166434, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.999291719780802, 'colsample_bytree': 0.401518896390569}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.93500	eval-mlogloss:0.92760
[1]	train-mlogloss:0.86677	eval-mlogloss:0.85127

[I 2026-07-19 09:04:13,493] Trial 12 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08249	eval-mlogloss:1.08363
[1]	train-mlogloss:1.07400	eval-mlogloss:1.07563
[2]	train-mlogloss:1.06354	eval-mlogloss:1.06601
[3]	train-mlogloss:1.04561	eval-mlogloss:1.04698
[4]	train-mlogloss:1.03824	eval-mlogloss:1.03927
[5]	train-mlogloss:1.02659	eval-mlogloss:1.02746
[6]	train-mlogloss:1.00953	eval-mlogloss:1.00880
[7]	train-mlogloss:0.99118	eval-mlogloss:0.98883

[I 2026-07-19 09:04:13,623] Trial 13 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.05842	eval-mlogloss:1.06010
[1]	train-mlogloss:1.04421	eval-mlogloss:1.04377
[2]	train-mlogloss:1.03130	eval-mlogloss:1.03481
[3]	train-mlogloss:1.00046	eval-mlogloss:1.00190
[4]	train-mlogloss:0.98426	eval-mlogloss:0.98705
[5]	train-mlogloss:0.95306	eval-mlogloss:0.95034
[6]	train-mlogloss:0.93093	eval-mlogloss:0.92818
[7]	train-mlogloss:0.89870	eval-mlogloss:0.89512

[I 2026-07-19 09:04:13,689] Trial 14 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.88531	eval-mlogloss:0.87452
[1]	train-mlogloss:0.80027	eval-mlogloss:0.78521

[I 2026-07-19 09:04:13,727] Trial 15 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.97608	eval-mlogloss:0.97322
[1]	train-mlogloss:0.92704	eval-mlogloss:0.91709

[I 2026-07-19 09:04:13,762] Trial 16 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05893	eval-mlogloss:1.05869
[1]	train-mlogloss:1.03955	eval-mlogloss:1.03866

[I 2026-07-19 09:04:13,795] Trial 17 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.89984	eval-mlogloss:0.89389
[1]	train-mlogloss:0.74859	eval-mlogloss:0.73200

[I 2026-07-19 09:04:13,831] Trial 18 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.89915	eval-mlogloss:0.88918
[1]	train-mlogloss:0.82316	eval-mlogloss:0.81032

[I 2026-07-19 09:04:13,865] Trial 19 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03369	eval-mlogloss:1.03461
[1]	train-mlogloss:0.97516	eval-mlogloss:0.97195

[I 2026-07-19 09:04:13,899] Trial 20 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07515	eval-mlogloss:1.07580
[1]	train-mlogloss:1.06327	eval-mlogloss:1.06504
[2]	train-mlogloss:1.04846	eval-mlogloss:1.05082
[3]	train-mlogloss:1.02320	eval-mlogloss:1.02448
[4]	train-mlogloss:1.01280	eval-mlogloss:1.01289
[5]	train-mlogloss:0.99625	eval-mlogloss:0.99649
[6]	train-mlogloss:0.97303	eval-mlogloss:0.97152
[7]	train-mlogloss:0.94754	eval-mlogloss:0.94405

[I 2026-07-19 09:04:13,970] Trial 21 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08198	eval-mlogloss:1.08298
[1]	train-mlogloss:1.07338	eval-mlogloss:1.07459
[2]	train-mlogloss:1.06262	eval-mlogloss:1.06443
[3]	train-mlogloss:1.04450	eval-mlogloss:1.04538
[4]	train-mlogloss:1.03673	eval-mlogloss:1.03677
[5]	train-mlogloss:1.02460	eval-mlogloss:1.02436
[6]	train-mlogloss:1.00750	eval-mlogloss:1.00594
[7]	train-mlogloss:0.98863	eval-mlogloss:0.98573

[I 2026-07-19 09:04:14,103] Trial 22 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08424	eval-mlogloss:1.08560
[1]	train-mlogloss:1.07618	eval-mlogloss:1.07803
[2]	train-mlogloss:1.06370	eval-mlogloss:1.06509
[3]	train-mlogloss:1.05008	eval-mlogloss:1.05123
[4]	train-mlogloss:1.03679	eval-mlogloss:1.03755
[5]	train-mlogloss:1.02383	eval-mlogloss:1.02376
[6]	train-mlogloss:1.01121	eval-mlogloss:1.01016
[7]	train-mlogloss:0.99874	eval-mlogloss:0.99719

[I 2026-07-19 09:04:14,167] Trial 23 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.98063	eval-mlogloss:0.97699
[1]	train-mlogloss:0.93095	eval-mlogloss:0.92812

[I 2026-07-19 09:04:14,211] Trial 24 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05029	eval-mlogloss:1.04945
[1]	train-mlogloss:1.02643	eval-mlogloss:1.02397

[I 2026-07-19 09:04:14,249] Trial 25 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.01713	eval-mlogloss:1.01597
[1]	train-mlogloss:0.98259	eval-mlogloss:0.97679

[I 2026-07-19 09:04:14,283] Trial 26 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05216	eval-mlogloss:1.05144
[1]	train-mlogloss:1.02808	eval-mlogloss:1.02640

[I 2026-07-19 09:04:14,326] Trial 27 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.01981	eval-mlogloss:1.01795
[1]	train-mlogloss:0.98683	eval-mlogloss:0.97720

[I 2026-07-19 09:04:14,364] Trial 28 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.93755	eval-mlogloss:0.93084
[1]	train-mlogloss:0.86050	eval-mlogloss:0.85805

[I 2026-07-19 09:04:14,401] Trial 29 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.95654	eval-mlogloss:0.95087
[1]	train-mlogloss:0.89036	eval-mlogloss:0.88247

[I 2026-07-19 09:04:14,439] Trial 30 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08454	eval-mlogloss:1.08598
[1]	train-mlogloss:1.07668	eval-mlogloss:1.07858
[2]	train-mlogloss:1.06450	eval-mlogloss:1.06602
[3]	train-mlogloss:1.05114	eval-mlogloss:1.05244
[4]	train-mlogloss:1.03809	eval-mlogloss:1.03904
[5]	train-mlogloss:1.02538	eval-mlogloss:1.02569
[6]	train-mlogloss:1.01301	eval-mlogloss:1.01236
[7]	train-mlogloss:1.00064	eval-mlogloss:0.99933
[8]	train-mlogloss:0.98888	eval-mlogloss:0.98688
[9]	train-mlogloss:0.97703	eval-mlogloss:0.97455
[10]	train-mlogloss:0.96640	eval-mlogloss:0.96395
[11]	train-mlogloss:0.95483	eval-mlogloss:0.95207
[12]	train-mlogloss:0.94507	eval-mlogloss:0.94203
[13]	train-mlogloss:0.93397	eval-mlogloss:0.93032
[14]	train-mlogloss:0.92307	eval-mlogloss:0.91858
[15]	train-mlogloss:0.91398	eval-mlogloss:0.90931
[16]	train-mlogloss:0.90495	eval-mlogloss:0.90000
[17]	train-mlogloss:0.89450	eval-mlogloss:0.88908
[18]	train-mlogloss:0.88583	eval-mlogloss:0.88000
[19]	train-mlogloss:0.87650	eval-mlogloss:0.87086
[20]	train-mlogloss:0.86812	eval-mlogloss:0.86219
[21]	train-mlogloss:0.85972	eval-mlogloss:0.85345
[22]	train-mlogloss:0.85008	eval-mlogloss:0.84304
[23]	train-mlogloss:0.84042	eval-mlogloss:0.83304
[24]	train-mlogloss:0.83105	eval-mlogloss:0.82297
[25]	train-mlogloss:0.82174	eval-mlogloss:0.81315
[26]	train-mlogloss:0.81332	eval-mlogloss:0.80444
[27]	train-mlogloss:0.80433	eval-mlogloss:0.79479
[28]	train-mlogloss:0.79546	eval-mlogloss:0.78540
[29]	train-mlogloss:0.78807	eval-mlogloss:0.77762
[30]	train-mlogloss:0.78236	eval-mlogloss:0.77203
[31]	train-mlogloss:0.77525	eval-mlogloss:0.76453

[I 2026-07-19 09:04:14,673] Trial 31 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.08552	eval-mlogloss:1.08701
[1]	train-mlogloss:1.07925	eval-mlogloss:1.08109
[2]	train-mlogloss:1.06815	eval-mlogloss:1.06940
[3]	train-mlogloss:1.05560	eval-mlogloss:1.05633
[4]	train-mlogloss:1.04354	eval-mlogloss:1.04401
[5]	train-mlogloss:1.03163	eval-mlogloss:1.03153
[6]	train-mlogloss:1.01999	eval-mlogloss:1.01911
[7]	train-mlogloss:1.00848	eval-mlogloss:1.00690
[8]	train-mlogloss:0.99746	eval-mlogloss:0.99486
[9]	train-mlogloss:0.98636	eval-mlogloss:0.98326
[10]	train-mlogloss:0.97679	eval-mlogloss:0.97317
[11]	train-mlogloss:0.96593	eval-mlogloss:0.96205
[12]	train-mlogloss:0.95678	eval-mlogloss:0.95242
[13]	train-mlogloss:0.94624	eval-mlogloss:0.94131
[14]	train-mlogloss:0.93595	eval-mlogloss:0.93007
[15]	train-mlogloss:0.92766	eval-mlogloss:0.92140
[16]	train-mlogloss:0.91926	eval-mlogloss:0.91261
[17]	train-mlogloss:0.90937	eval-mlogloss:0.90223
[18]	train-mlogloss:0.90108	eval-mlogloss:0.89344
[19]	train-mlogloss:0.89252	eval-mlogloss:0.88505
[20]	train-mlogloss:0.88465	eval-mlogloss:0.87681
[21]	train-mlogloss:0.87683	eval-mlogloss:0.86857
[22]	train-mlogloss:0.86767	eval-mlogloss:0.85855
[23]	train-mlogloss:0.85844	eval-mlogloss:0.84898
[24]	train-mlogloss:0.84948	eval-mlogloss:0.83915
[25]	train-mlogloss:0.84059	eval-mlogloss:0.82979
[26]	train-mlogloss:0.83280	eval-mlogloss:0.82132
[27]	train-mlogloss:0.82422	eval-mlogloss:0.81197
[28]	train-mlogloss:0.81581	eval-mlogloss:0.80303
[29]	train-mlogloss:0.80886	eval-mlogloss:0.79570
[30]	train-mlogloss:0.80400	eval-mlogloss:0.79103
[31]	train-mlogloss:0.79751	eval-mlogloss:0.78441
[32]	train-mlogloss:0.78944	eval-mlogloss:0.77592
[33]	train-mlogloss:0.78148	eval-mlogloss:0.76708
[34]	train-mlogloss:0.77528	eval-mlogloss:0.76077
[35]	train-mlogloss:0.76765	eval-mlogloss:0.75238
[36]	train-mlogloss:0.76091	eval-mlogloss:0.74538
[37]	train-mlogloss:0.75337	eval-mlogloss:0.73709
[38]	train-mlogloss:0.74592	eval-mlogloss:0.72893
[39]	train-mlogloss:0.73859	eval-mlogloss:0.72134
[40]	train-mlogloss:0.73271	eval-mlogloss:0.71513
[41]	train-mlogloss:0.72548	eval-mlogloss:0.70750
[42]	train-mlogloss:0.71844	eval-mlogloss:0.69978
[43]	train-mlogloss:0.71139	eval-mlogloss:0.69235
[44]	train-mlogloss:0.70598	eval-mlogloss:0.68689
[45]	train-mlogloss:0.69909	eval-mlogloss:0.67960
[46]	train-mlogloss:0.69228	eval-mlogloss:0.67222
[47]	train-mlogloss:0.68638	eval-mlogloss:0.66602
[48]	train-mlogloss:0.67982	eval-mlogloss:0.65930
[49]	train-mlogloss:0.67325	eval-mlogloss:0.65210
[50]	train-mlogloss:0.66698	eval-mlogloss:0.64519
[51]	train-mlogloss:0.66140	eval-mlogloss:0.63930
[52]	train-mlogloss:0.65726	eval-mlogloss:0.63506
[53]	train-mlogloss:0.65115	eval-mlogloss:0.62849
[54]	train-mlogloss:0.64684	eval-mlogloss:0.62392
[55]	train-mlogloss:0.64186	eval-mlogloss:0.61873
[56]	train-mlogloss:0.63699	eval-mlogloss:0.61356
[57]	train-mlogloss:0.63218	eval-mlogloss:0.60863
[58]	train-mlogloss:0.62769	eval-mlogloss:0.60423
[59]	train-mlogloss:0.62181	eval-mlogloss:0.59799
[60]	train-mlogloss:0.61618	eval-mlogloss:0.59197
[61]	train-mlogloss:0.61151	eval-mlogloss:0.58699
[62]	train-mlogloss:0.60592	eval-mlogloss:0.58101
[63]	train-mlogloss:0.60044	eval-mlogloss:0.57517
[64]	train-mlogloss:0.59500	eval-mlogloss:0.56940
[65]	train-mlogloss:0.58957	eval-mlogloss:0.56372
[66]	train-mlogloss:0.58423	eval-mlogloss:0.55811
[67]	train-mlogloss:0.58016	eval-mlogloss:0.55389
[68]	train-mlogloss:0.57620	eval-mlogloss:0.55002
[69]	train-mlogloss:0.57173	eval-mlogloss:0.54539
[70]	train-mlogloss:0.56731	eval-mlogloss:0.54050
[71]	train-mlogloss:0.56217	eval-mlogloss:0.53479
[72]	train-mlogloss:0.55914	eval-mlogloss:0.53153
[73]	train-mlogloss:0.55416	eval-mlogloss:0.52635
[74]	train-mlogloss:0.54927	eval-mlogloss:0.52126
[75]	train-mlogloss:0.54443	eval-mlogloss:0.51601
[76]	train-mlogloss:0.54145	eval-mlogloss:0.51320
[77]	train-mlogloss:0.53670	eval-mlogloss:0.50825
[78]	train-mlogloss:0.53285	eval-mlogloss:0.50411
[79]	train-mlogloss:0.52832	eval-mlogloss:0.49918
[80]	train-mlogloss:0.52442	eval-mlogloss:0.49480
[81]	train-mlogloss:0.51977	eval-mlogloss:0.48996
[82]	train-mlogloss:0.51542	eval-mlogloss:0.48519
[83]	train-mlogloss:0.51098	eval-mlogloss:0.48024
[84]	train-mlogloss:0.50664	eval-mlogloss:0.47558
[85]	train-mlogloss:0.50364	eval-mlogloss:0.47263
[86]	train-mlogloss:0.49931	eval-mlogloss:0.46782
[87]	train-mlogloss:0.49615	eval-mlogloss:0.46450
[88]	train-mlogloss:0.49246	eval-mlogloss:0.46046
[89]	train-mlogloss:0.48832	eval-mlogloss:0.45595
[90]	train-mlogloss:0.48426	eval-mlogloss:0.45167
[91]	train-mlogloss:0.48089	eval-mlogloss:0.44804
[92]	train-mlogloss:0.47735	eval-mlogloss:0.44423
[93]	train-mlogloss:0.47323	eval-mlogloss:0.43971
[94]	train-mlogloss:0.46925	eval-mlogloss:0.43538
[95]	train-mlogloss:0.46622	eval-mlogloss:0.43196
[96]	train-mlogloss:0.46240	eval-mlogloss:0.42782
[97]	train-mlogloss:0.45860	eval-mlogloss:0.42376
[98]	train-mlogloss:0.45499	eval-mlogloss:0.41978
[99]	train-mlogloss:0.45126	eval-mlogloss:0.41577
[100]	train-mlogloss:0.44831	eval-mlogloss:0.41258
[101]	train-mlogloss:0.44466	eval-mlogloss:0.40875
[102]	train-mlogloss:0.44095	eval-mlogloss:0.40488
[103]	train-mlogloss:0.43834	eval-mlogloss:0.40219
[104]	train-mlogloss:0.43560	eval-mlogloss:0.39954
[105]	train-mlogloss:0.43253	eval-mlogloss:0.39605
[106]	train-mlogloss:0.42905	eval-mlogloss:0.39241
[107]	train-mlogloss:0.42571	eval-mlogloss:0.38873
[108]	train-mlogloss:0.42228	eval-mlogloss:0.38491
[109]	train-mlogloss:0.41980	eval-mlogloss:0.38227
[110]	train-mlogloss:0.41647	eval-mlogloss:0.37849
[111]	train-mlogloss:0.41320	eval-mlogloss:0.37481
[112]	train-mlogloss:0.41088	eval-mlogloss:0.37226
[113]	train-mlogloss:0.40852	eval-mlogloss:0.36963
[114]	train-mlogloss:0.40552	eval-mlogloss:0.36624
[115]	train-mlogloss:0.40266	eval-mlogloss:0.36294
[116]	train-mlogloss:0.40019	eval-mlogloss:0.36027
[117]	train-mlogloss:0.39749	eval-mlogloss:0.35743
[118]	train-mlogloss:0.39460	eval-mlogloss:0.35416
[119]	train-mlogloss:0.39239	eval-mlogloss:0.35189
[120]	train-mlogloss:0.39015	eval-mlogloss:0.34939
[121]	train-mlogloss:0.38721	eval-mlogloss:0.34613
[122]	train-mlogloss:0.38459	eval-mlogloss:0.34316
[123]	train-mlogloss:0.38251	eval-mlogloss:0.34084
[124]	train-mlogloss:0.38035	eval-mlogloss:0.33863
[125]	train-mlogloss:0.37823	eval-mlogloss:0.33637
[126]	train-mlogloss:0.37616	eval-mlogloss:0.33425
[127]	train-mlogloss:0.37404	eval-mlogloss:0.33192

[I 2026-07-19 09:04:15,591] Trial 32 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:1.06883	eval-mlogloss:1.06917
[1]	train-mlogloss:1.05435	eval-mlogloss:1.05528
[2]	train-mlogloss:1.03564	eval-mlogloss:1.03882
[3]	train-mlogloss:1.00471	eval-mlogloss:1.00578
[4]	train-mlogloss:0.99263	eval-mlogloss:0.99220
[5]	train-mlogloss:0.97305	eval-mlogloss:0.97241
[6]	train-mlogloss:0.94451	eval-mlogloss:0.94192
[7]	train-mlogloss:0.91418	eval-mlogloss:0.90928

[I 2026-07-19 09:04:15,650] Trial 33 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.05021	eval-mlogloss:1.04931
[1]	train-mlogloss:1.02728	eval-mlogloss:1.02729

[I 2026-07-19 09:04:15,685] Trial 34 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05765	eval-mlogloss:1.05735
[1]	train-mlogloss:1.03800	eval-mlogloss:1.03467

[I 2026-07-19 09:04:15,723] Trial 35 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03328	eval-mlogloss:1.03143
[1]	train-mlogloss:1.00200	eval-mlogloss:0.99831

[I 2026-07-19 09:04:15,769] Trial 36 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06816	eval-mlogloss:1.07104
[1]	train-mlogloss:1.05184	eval-mlogloss:1.05726
[2]	train-mlogloss:1.03249	eval-mlogloss:1.04029
[3]	train-mlogloss:1.00238	eval-mlogloss:1.00770
[4]	train-mlogloss:0.98811	eval-mlogloss:0.99571
[5]	train-mlogloss:0.96826	eval-mlogloss:0.97760
[6]	train-mlogloss:0.94067	eval-mlogloss:0.94736
[7]	train-mlogloss:0.91143	eval-mlogloss:0.91595

[I 2026-07-19 09:04:15,908] Trial 37 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.99910	eval-mlogloss:0.99652
[1]	train-mlogloss:0.95540	eval-mlogloss:0.94951

[I 2026-07-19 09:04:15,945] Trial 38 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.04512	eval-mlogloss:1.04520
[1]	train-mlogloss:1.02119	eval-mlogloss:1.01777

[I 2026-07-19 09:04:15,981] Trial 39 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03577	eval-mlogloss:1.03355
[1]	train-mlogloss:1.00546	eval-mlogloss:1.00514

[I 2026-07-19 09:04:16,023] Trial 40 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08250	eval-mlogloss:1.08385
[1]	train-mlogloss:1.07352	eval-mlogloss:1.07539
[2]	train-mlogloss:1.05958	eval-mlogloss:1.06105
[3]	train-mlogloss:1.04440	eval-mlogloss:1.04570
[4]	train-mlogloss:1.02957	eval-mlogloss:1.03044
[5]	train-mlogloss:1.01515	eval-mlogloss:1.01528
[6]	train-mlogloss:1.00116	eval-mlogloss:1.00020
[7]	train-mlogloss:0.98721	eval-mlogloss:0.98550

[I 2026-07-19 09:04:16,085] Trial 41 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08349	eval-mlogloss:1.08499
[1]	train-mlogloss:1.07523	eval-mlogloss:1.07704
[2]	train-mlogloss:1.06217	eval-mlogloss:1.06350
[3]	train-mlogloss:1.04779	eval-mlogloss:1.04890
[4]	train-mlogloss:1.03374	eval-mlogloss:1.03445
[5]	train-mlogloss:1.02008	eval-mlogloss:1.02008
[6]	train-mlogloss:1.00674	eval-mlogloss:1.00575
[7]	train-mlogloss:0.99358	eval-mlogloss:0.99208

[I 2026-07-19 09:04:16,143] Trial 42 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.07228	eval-mlogloss:1.07278
[1]	train-mlogloss:1.05928	eval-mlogloss:1.06072
[2]	train-mlogloss:1.04303	eval-mlogloss:1.04569
[3]	train-mlogloss:1.01526	eval-mlogloss:1.01660
[4]	train-mlogloss:1.00376	eval-mlogloss:1.00508
[5]	train-mlogloss:0.98593	eval-mlogloss:0.98733
[6]	train-mlogloss:0.96051	eval-mlogloss:0.96022
[7]	train-mlogloss:0.93276	eval-mlogloss:0.93036

[I 2026-07-19 09:04:16,284] Trial 43 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04085	eval-mlogloss:1.03975
[1]	train-mlogloss:1.01035	eval-mlogloss:1.00882

[I 2026-07-19 09:04:16,337] Trial 44 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07457	eval-mlogloss:1.07519
[1]	train-mlogloss:1.06272	eval-mlogloss:1.06258
[2]	train-mlogloss:1.04742	eval-mlogloss:1.04769
[3]	train-mlogloss:1.02114	eval-mlogloss:1.01969
[4]	train-mlogloss:1.01066	eval-mlogloss:1.00860
[5]	train-mlogloss:0.99426	eval-mlogloss:0.99227
[6]	train-mlogloss:0.97033	eval-mlogloss:0.96656
[7]	train-mlogloss:0.94424	eval-mlogloss:0.93826

[I 2026-07-19 09:04:16,403] Trial 45 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04151	eval-mlogloss:1.04129
[1]	train-mlogloss:1.01087	eval-mlogloss:1.01364

[I 2026-07-19 09:04:16,445] Trial 46 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05090	eval-mlogloss:1.05063
[1]	train-mlogloss:1.02910	eval-mlogloss:1.02852

[I 2026-07-19 09:04:16,481] Trial 47 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.84294	eval-mlogloss:0.82770
[1]	train-mlogloss:0.75048	eval-mlogloss:0.73708

[I 2026-07-19 09:04:16,531] Trial 48 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07098	eval-mlogloss:1.07168
[1]	train-mlogloss:1.05719	eval-mlogloss:1.05913

[I 2026-07-19 09:04:16,573] Trial 49 pruned. Trial was pruned at iteration 2.

Best trial: {'lambda': 0.1768922998962018, 'alpha': 0.030624106999035852, 'eta': 0.03152436890744786, 'gamma': 0.07440134925912152, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.6218678294078834, 'colsample_bytree': 0.43426403773185257}
Best accuracy: 1.0

### Install XGBoost Integration for Optuna

In [71]:
! pip install optuna-integration[xgboost]

Requirement already satisfied: optuna-integration[xgboost] in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (4.9.0)
Requirement already satisfied: optuna in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna-integration[xgboost]) (4.9.0)
Requirement already satisfied: xgboost in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna-integration[xgboost]) (3.2.0)
Requirement already satisfied: alembic>=1.5.0 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna->optuna-integration[xgboost]) (1.18.5)
Requirement already satisfied: colorlog in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna->optuna-integration[xgboost]) (6.11.0)
Requirement already satisfied: numpy in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna->optuna-integration[xgboost]) (2.4.5)
Requirement already satisfied: packaging>=20.0 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna->optuna-integration[xgboost]) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna->optuna-integration[xgboost]) (2.0.51)
Requirement already satisfied: tqdm in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: scipy in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from xgboost->optuna-integration[xgboost]) (1.17.1)
Requirement already satisfied: Mako in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.5.3)
Requirement already satisfied: colorama in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from colorlog->optuna->optuna-integration[xgboost]) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in d:\pendrive 32 gb\game\ai_projects\machine learning\venv\lib\site-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (2.1.5)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### Plot Intermediate Values
Shows how each trial's `eval-mlogloss` evolves across boosting rounds.
- Lines that drop fast and stay low = good trials
- Lines that plateau high = correctly pruned early
- Pruned trials appear shorter — they were stopped before round 300

In [72]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()

---
## Summary

```
Optuna — Key Points:

  Core Workflow:
    1. Define objective(trial) → returns a scalar score
    2. study = optuna.create_study(direction='maximize')
    3. study.optimize(objective, n_trials=N)
    4. study.best_trial.params → use these to train final model

  Suggest API:
    trial.suggest_int('name', low, high)
    trial.suggest_float('name', low, high, log=True)
    trial.suggest_categorical('name', ['a', 'b', 'c'])

  Samplers:
    TPESampler   → Bayesian (default, recommended)
    RandomSampler → baseline / parallel jobs
    GridSampler  → small explicit grids

  Pruners (stop bad trials early):
    MedianPruner              → stop if below median at checkpoint
    SuccessiveHalvingPruner   → keep top 50% at each stage

  Visualizations:
    plot_optimization_history  → score over trials
    plot_parallel_coordinate   → all params vs score
    plot_param_importances     → which params matter most
    plot_intermediate_values   → per-round scores (pruning view)

  Multi-model trick:
    suggest_categorical('classifier', ['SVM','RF','GB'])
    → Optuna finds best model + best params in one study
```